client/packages/client-fusion/src/Connect.ts
client/packages/client-fusion/src/form/BinderNode.ts
client/packages/client-fusion/src/form/Validators.ts
client/packages/client-fusion/test/Connect.test.ts
client/packages/client-fusion/test/form/Binder.test.ts
client/packages/client-fusion/test/form/Validators.test.ts

Cherry-pick missing commits in the `flow-client` folder.
Rebase, don't Squash.

cherry picks the missing commits

---

client/packages/client-common/package.json
client/packages/client-fusion/package.json

chore: make lint only check .ts files

---

client/tsconfig.json

Enabled the config options to generate sourcemaps for better DX and to avoid console warnings in `web-test-runner`.
Fixes vaadin/flow#11424
- Bugfix

fix: enable generation of sourcemap files

---

.github/workflows/frontend-release.yml
frontend/scripts/bump.sh

chore(frontend): rename token variable

---

frontend/packages/common-frontend/LICENSE
frontend/packages/common-frontend/README.md
frontend/packages/common-frontend/package.json
frontend/packages/form/LICENSE
frontend/packages/form/README.md
frontend/packages/form/package.json
frontend/packages/fusion-frontend/LICENSE
frontend/packages/fusion-frontend/README.md
frontend/packages/fusion-frontend/package.json

For each package:
- Add README file,
- Add LICENSE file,
- Use correct link to GitHub.

chore(frontend): improve packages for npm

---

scripts/bump/exec.sh

Fix version bump script to be able to do a release.

chore(ci): fix version bump script

---

lerna.json
packages/ts/form/package.json
packages/ts/form/src/index.ts
packages/ts/fusion-frontend/package.json
packages/ts/fusion-frontend/src/index.ts
packages/ts/generator-typescript-cli/package.json
packages/ts/generator-typescript-core/package.json
packages/ts/generator-typescript-plugin-backbone/package.json
packages/ts/generator-typescript-plugin-barrel/package.json
packages/ts/generator-typescript-plugin-client/package.json
packages/ts/generator-typescript-utils/package.json

Enables publishing the new packages to npm.

chore: add missing publishConfig to new packages

---

packages/java/parser-jvm-core/src/main/java/com/vaadin/fusion/parser/core/ClassRefRelativeTypeSignature.java
packages/java/parser-jvm-core/src/main/java/com/vaadin/fusion/parser/core/ReflectedClass.java
packages/java/parser-jvm-core/src/main/java/com/vaadin/fusion/parser/core/RelativeTypeParameter.java
packages/java/parser-jvm-core/src/main/java/com/vaadin/fusion/parser/core/RelativeTypeSignature.java
packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/fusion/parser/plugins/backbone/SchemaProcessor.java
packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/fusion/parser/plugins/backbone/generics/Endpoint.java
packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/fusion/parser/plugins/backbone/generics/GenericsBareEndpoint.java
packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/fusion/parser/plugins/backbone/generics/GenericsExtendedEndpoint.java
packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/fusion/parser/plugins/backbone/generics/GenericsMethodsEndpoint.java
packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/fusion/parser/plugins/backbone/generics/GenericsRefEndpoint.java
packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/fusion/parser/plugins/backbone/generics/GenericsRefEntity.java
packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/fusion/parser/plugins/backbone/generics/GenericsTest.java
packages/java/parser-jvm-plugin-backbone/src/test/resources/com/vaadin/fusion/parser/plugins/backbone/datetime/openapi.json
packages/java/parser-jvm-plugin-backbone/src/test/resources/com/vaadin/fusion/parser/plugins/backbone/generics/openapi.json

feat(java/parser-jvm-plugin-backbone): make generic types produce correct schema

---

packages/java/maven-plugin/src/main/java/com/vaadin/fusion/maven/ParserConfiguration.java
packages/java/maven-plugin/src/main/java/com/vaadin/fusion/maven/ParserProcessor.java

fix: NPE in parser because of null plugins

---

README.md

rename Fusion to Hilla in README

chore: rename fusion to hilla in README

---

.github/workflows/release.yml

Add a manual workflow that triggers the release

add dispatch workflow

---

README.md

chore: update hilla maven version to 1.0.0.beta3

---

README.md

chore: update README badge to 1.0.3

---

scripts/bump/exec.sh

- Fixes GNU sed backup extension error
- Use X.Y.Z-suffix npm version format for X.Y.Z.suffix git tags
- Ensure the script does not commit new files

chore: improve version bump script

---

packages/ts/hilla-frontend/src/FluxConnection.ts
packages/ts/hilla-frontend/test/Connect.test.ts
packages/ts/hilla-frontend/test/FluxConnection.test.ts

feat(ts/hilla-frontend): Require feature flag to use push

---

packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/core/Parser.java
packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/core/Plugin.java
packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/core/PluginManager.java
packages/java/parser-jvm-plugin-transfertypes/src/main/java/dev/hilla/parser/plugins/transfertypes/TransferTypesPlugin.java

Modifies the plugin API to allow to execute some code before collecting endpoints and entities.

feat(parser): add preprocessing capabilities to plugins

---

packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoReflectionModel.java
packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoSourceModel.java
packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassRefSignatureModel.java
packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/SpecializedModel.java
packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/BaseSignatureModelTests.java
packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/ClassInfoModelTests.java
packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/ClassRefSignatureModelTests.java
packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/SchemaProcessor.java
packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/simpletype/SimpleTypeEndpoint.java
packages/java/parser-jvm-plugin-backbone/src/test/resources/dev/hilla/parser/plugins/backbone/simpletype/openapi.json
packages/ts/generator-typescript-plugin-backbone/test/simple-type/SimpleType.json
packages/ts/generator-typescript-plugin-backbone/test/simple-type/fixtures/SimpleTypeEndpoint.snap.ts

fix(parser): emit number schema for BigDecimal type

---

scripts/bump/exec.sh

The `exec.sh` script is modified to also update Java files when a new `npm` version of packages is released.
Also, make sure that all `find` command only operate on files, as if we symlink something in the repo, `sed` would undo the symlink.
Closes #506

feat: add updater for npm versions in Java sources

---

packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/core/ScanElementsCollector.java
packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/ParserTests.java
packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/dependency/DependencyEndpoint.java
packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/dependency/DependencyEntityOne.java
packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/dependency/DependencyEntityThree.java
packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/dependency/DependencyEntityTwo.java
packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/dependency/DependencyPlugin.java
packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/dependency/PluginDependencyEntity.java
packages/java/parser-jvm-plugin-nonnull/src/test/resources/dev/hilla/parser/plugins/nonnull/extended/openapi.json

fix(parser-jvm-core): only parse entities of endpoint methods or entity fields

---

package-lock.json
packages/ts/form/package.json
packages/ts/hilla-frontend/package.json

This is the combination of versions that allowed me to pass the tests again.

chore: avoid conflicting versions of `@lit/reactive-element` to allow tests to pass again

---

package-lock.json
packages/java/maven-plugin/src/main/java/dev/hilla/maven/GeneratorProcessor.java
packages/java/maven-plugin/src/main/java/dev/hilla/maven/GeneratorShellRunner.java
packages/ts/generator-typescript-cli/package.json
packages/ts/generator-typescript-cli/src/index.ts
packages/ts/generator-typescript-cli/src/utils.ts

This PR refactors existing code to pass OpenAPI JSON though standard input.
Fixes #533

fix(engine): pass OpenAPI JSON to generator using stdin to avoid size limitations

---

packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/SchemaProcessor.java
packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/bare/BareTypeEndpoint.java
packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/bare/BareTypeTest.java
packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/bare/Endpoint.java
packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/wildcard/Endpoint.java
packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/wildcard/WildcardTypeEndpoint.java
packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/wildcard/WildcardTypeTest.java
packages/java/parser-jvm-plugin-backbone/src/test/resources/dev/hilla/parser/plugins/backbone/bare/openapi.json
packages/java/parser-jvm-plugin-backbone/src/test/resources/dev/hilla/parser/plugins/backbone/wildcard/openapi.json

fix(parser-jvm-plugin-backbone): add a fallback for bare types

---

packages/java/endpoint/src/main/java/dev/hilla/generator/typescript/ModelGenerator.java
packages/java/endpoint/src/test/java/dev/hilla/generator/tsmodel/TsFormEndpoint.java
packages/java/endpoint/src/test/resources/dev/hilla/generator/tsmodel/expected-TsFormEndpoint.ts
packages/ts/generator-typescript-plugin-model/src/ModelSchemaProcessor.ts
packages/ts/generator-typescript-plugin-model/test/model/Model.json
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityModel.snap.ts

fix: use correct model for unknown value

---

packages/java/maven-plugin/src/main/java/dev/hilla/maven/EndpointCodeGeneratorMojo.java
packages/java/maven-plugin/src/main/java/dev/hilla/maven/ParserProcessor.java

Addresses the debugging issue from #541.

refactor(maven-plugin): create OpenAPI file during generation

---

lerna.json
package-lock.json
packages/ts/form/package.json
packages/ts/form/src/index.ts
packages/ts/generator-typescript-cli/package.json
packages/ts/generator-typescript-core/package.json
packages/ts/generator-typescript-plugin-backbone/package.json
packages/ts/generator-typescript-plugin-barrel/package.json
packages/ts/generator-typescript-plugin-client/package.json
packages/ts/generator-typescript-plugin-model/package.json
packages/ts/generator-typescript-utils/package.json
packages/ts/hilla-frontend/package.json
packages/ts/hilla-frontend/src/index.ts

chore(release): npm version 1.1.11

---

pom.xml

chore: update vaadin-parent to 2.1.0

---

lerna.json
package-lock.json
packages/java/endpoint/src/main/java/dev/hilla/EndpointController.java
packages/java/engine-runtime/src/main/java/dev/hilla/internal/TaskGenerateHillaImpl.java
packages/ts/form/package.json
packages/ts/form/src/index.ts
packages/ts/generator-typescript-cli/package.json
packages/ts/generator-typescript-core/package.json
packages/ts/generator-typescript-plugin-backbone/package.json
packages/ts/generator-typescript-plugin-barrel/package.json
packages/ts/generator-typescript-plugin-client/package.json
packages/ts/generator-typescript-plugin-model/package.json
packages/ts/generator-typescript-plugin-push/package.json
packages/ts/generator-typescript-utils/package.json
packages/ts/hilla-frontend/package.json
packages/ts/hilla-frontend/src/index.ts

This reverts commit c32428dbdbf1a7da19325b55477ee6401059e966.

Revert "chore(release): npm version 1.1.14"

---

packages/java/endpoint/src/test/java/dev/hilla/frontend/NodeTasksEndpointTest.java
packages/java/tests/pom.xml
packages/java/tests/spring/endpoints-custom-client/frontend/index.ts
packages/java/tests/spring/pom.xml
packages/java/tests/spring/security-contextpath/pom.xml
packages/java/tests/spring/security-jwt/pom.xml
packages/java/tests/spring/security-urlmapping/pom.xml
packages/java/tests/spring/security/pom.xml
pom.xml

* chore: resolve circular dependency
* chore: add lumo dependency
* chore: component view dependency
* chore: move component dependency to test root
* chore:add custom-field dependency

chore: resolve circular dependency  (#570) (CP: 1.3)

---

packages/java/maven-plugin/pom.xml

chore: fix wrong scope for org.apache.maven dep

---

.github/workflows/validation.yml

(cherry picked from commit d9ed286db82b76fe844ee1e4a5db5b8f55e047c3)

build: simplify build matrix (#657)

---

packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java
packages/java/parser-jvm-plugin-nonnull/src/test/java/dev/hilla/parser/plugins/nonnull/basic/BasicEndpoint.java
packages/java/parser-jvm-plugin-nonnull/src/test/java/dev/hilla/parser/plugins/nonnull/nonnullapi/NonNullApiEndpoint.java
packages/java/parser-jvm-plugin-nonnull/src/test/resources/dev/hilla/parser/plugins/nonnull/basic/openapi.json
packages/java/parser-jvm-plugin-nonnull/src/test/resources/dev/hilla/parser/plugins/nonnull/nonnullapi/openapi.json

fix: make `Optional`s always nullable

---

packages/java/endpoint/src/main/java/dev/hilla/generator/GenerationOutputDirectory.java

A new generated file is created in https://github.com/vaadin/flow/pull/12782. Found this list of files to preserve, added the new one to the list.
Fixes #742

fix: preserve vaadin-featureflags.ts

---

scripts/bump/protection-remap.js

enable the branch protection rule to everyone when reenable the restrictions using script

chore: enable the restrictions to everyone

---

package-lock.json
packages/java/tests/csrf-context/package.json
packages/java/tests/csrf/package.json

pick commit https://github.com/vaadin/hilla/pull/721

chore(release): make package-lock.json npm 8 compatible

---

packages/java/endpoint/src/main/java/dev/hilla/springnative/HillaHintsRegistrar.java
packages/java/endpoint/src/test/java/dev/hilla/springnative/HillaHintsRegistrarTest.java
packages/java/endpoint/src/test/resources/dev/hilla/springnative/openapi-customtype.json
packages/java/endpoint/src/test/resources/dev/hilla/springnative/openapi-innertype.json
packages/java/endpoint/src/test/resources/dev/hilla/springnative/openapi-nocustomtypes.json
packages/java/endpoint/src/test/resources/dev/hilla/springnative/openapi-referring-customtypes.json

fix: Fix openapi parsing when there are no custom types

---

packages/java/engine-core/src/main/java/dev/hilla/engine/GeneratorShellRunner.java

fix: executing Node in Windows with spaces in path

---

lerna.json
package-lock.json
packages/java/endpoint/src/main/java/dev/hilla/EndpointController.java
packages/java/engine-core/src/main/java/dev/hilla/engine/GeneratorProcessor.java
packages/ts/form/package.json
packages/ts/form/src/index.ts
packages/ts/generator-typescript-cli/package.json
packages/ts/generator-typescript-core/package.json
packages/ts/generator-typescript-plugin-backbone/package.json
packages/ts/generator-typescript-plugin-barrel/package.json
packages/ts/generator-typescript-plugin-client/package.json
packages/ts/generator-typescript-plugin-model/package.json
packages/ts/generator-typescript-plugin-push/package.json
packages/ts/generator-typescript-utils/package.json
packages/ts/hilla-frontend/package.json
packages/ts/hilla-frontend/src/index.ts

chore(release): npm version 2.1.0-alpha3

---

packages/ts/form/src/BinderNode.ts
packages/ts/form/src/Field.ts
packages/ts/form/test/Field.test.ts
packages/ts/form/test/Validation.test.ts

fix(form): error message not displayed in invalid fields

---

packages/java/engine-core/src/main/java/dev/hilla/engine/EngineConfiguration.java
packages/java/engine-runtime/src/main/java/dev/hilla/internal/AbstractTaskEndpointGenerator.java
packages/java/engine-runtime/src/test/java/dev/hilla/internal/TaskTest.java

Fixes https://github.com/vaadin/hilla/issues/934

fix: rebuild engine configuration at least once per run

---

.gitignore
packages/ts/generator-typescript-plugin-push/src/PushProcessor.ts
packages/ts/generator-typescript-utils/package.json
packages/ts/generator-typescript-utils/src/memoize.ts

fix: only add Subscription import when used

---

packages/java/endpoint/src/main/java/dev/hilla/Nullable.java
packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPluginConfig.java
packages/java/tests/spring/endpoints-latest-java/src/main/java/com/vaadin/flow/connect/AppEndpoint.java
packages/java/tests/spring/endpoints/src/main/java/com/vaadin/flow/connect/AppEndpoint.java
packages/java/tests/spring/endpoints/src/main/java/com/vaadin/flow/connect/FluxEndpoint.java
packages/java/tests/spring/endpoints/src/main/java/com/vaadin/flow/connect/PackagePrivateEndpoint.java
packages/java/tests/spring/endpoints/src/main/java/com/vaadin/flow/connect/PagedEndpoint.java

feat: add Nullable annotation

---

README.md

Remove outdated link to docs

---

packages/java/endpoint/src/main/java/dev/hilla/EndpointInvoker.java

Use Spring Validator when available
(cherry picked from commit b9f8364b0fbad59d2088ca6b833f9fdd710880bb)

feat: use Spring Validator when available (#973) (CP: 1.3)

---

packages/java/gradle-plugin/build.gradle
packages/java/gradle-plugin/pom.xml
packages/java/gradle-plugin/src/functionalTest/kotlin/dev/hilla/gradle/plugin/SingleModuleTest.kt
packages/java/gradle-plugin/src/main/kotlin/dev/hilla/gradle/plugin/EngineInitAppTask.kt
packages/java/maven-plugin/pom.xml
packages/java/maven-plugin/src/main/java/dev/hilla/maven/InitAppMojo.java
packages/java/plugin-base/pom.xml
packages/java/plugin-base/src/main/java/dev/hilla/plugin/base/HillaAppInitUtility.java
packages/java/plugin-base/src/test/java/dev/hilla/plugin/base/HillaAppInitUtilityTest.java
pom.xml

Internal improvements:
- renaming hilla-plugin-base to plugin-base
- improving the detection of Lit/React starter dependency for both maven and gradle
- refactoring and renaming classes/methods
- improving the scan for the class annotated with `@SpringBootApplication`
- adding tests
Fixes #961

chore: improve app init feature

---

package-lock.json
packages/ts/generator-typescript-plugin-backbone/test/complex-hierarchy/fixtures/ComplexHierarchyEndpoint.snap.ts
packages/ts/generator-typescript-plugin-backbone/test/complex-hierarchy/fixtures/Model.entity.snap.ts
packages/ts/generator-typescript-plugin-backbone/test/complex-hierarchy/fixtures/ParentModel.entity.snap.ts
packages/ts/generator-typescript-plugin-backbone/test/complex-type/fixtures/ComplexTypeEndpoint.snap.ts
packages/ts/generator-typescript-plugin-backbone/test/custom-client/fixtures/CustomClientEndpoint.snap.ts
packages/ts/generator-typescript-plugin-backbone/test/enum-type/fixtures/EnumTypeEndpoint.snap.ts
packages/ts/generator-typescript-plugin-backbone/test/name-clash/fixtures/NameClashEndpoint.snap.ts
packages/ts/generator-typescript-plugin-backbone/test/simple-type/fixtures/SimpleTypeEndpoint.snap.ts
packages/ts/generator-typescript-plugin-barrel/test/basic/fixtures/barrel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormAnnotationsModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormArrayTypesModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormDataPrimitivesModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityHierarchyModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityIdModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEnumTypesModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormNonnullTypesModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormOptionalTypesModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormRecordTypesModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormTemporalTypesModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormValidationConstraintsModel.snap.ts
packages/ts/generator-typescript-plugin-push/test/push-type/fixtures/PushTypeEndpoint.snap.ts
packages/ts/generator-typescript-plugin-push/test/push-type/fixtures/PushTypeOnlyEndpoint.snap.ts
packages/ts/generator-typescript-utils/src/dependencies/ImportManager.ts

* Add .js to imports
* Fix formatting
* Add missing .js
* Fix .js added twice to some imports
* Remove leaked dev logs
* test(generator): update snapshots for other plugins
---------

feat: support ES-module application by adding .js to generated imports (#817) (CP: 1.3)

---

.github/workflows/skip-validation.yml
.github/workflows/validation.yml
packages/java/tests/pom.xml
packages/java/tests/spring/pom.xml

build: add Windows run and skip-success workflows

---

packages/java/tests/gradle/single-module-tests/src/test/java/dev/hilla/gradle/plugin/test/ProductionBuildFunctionalIT.java

Use GradleRunner in gradle IT to make it OS agnostic.

test: use GradleRunner in tests to make it OS-agnostic

---

packages/java/tests/gradle/single-module-tests/src/test/java/dev/hilla/gradle/plugin/test/ProductionBuildFunctionalIT.java
packages/ts/generator-typescript-cli/src/GeneratorIO.ts

fix(generator-typescript-cli): fix generator plugin import on Windows

---

packages/java/gradle-plugin/pom-portal.xml
pom.xml

chore: add portal pom to deploy gradle plugin in pre-releases repo

---

packages/ts/hilla-frontend/src/Connect.ts
packages/ts/hilla-frontend/test/Connect.test.ts

fix: throw error based on http code even if there is body

---

packages/ts/form/package.json
packages/ts/form/src/Binder.ts
packages/ts/form/src/BinderRoot.ts
packages/ts/form/src/index.ts
packages/ts/form/test/Validation.test.ts

feat: extract binder superclass without context element

---

packages/ts/form/src/Validators.ts
packages/ts/form/test/Validators.test.ts

Note: **does not** fix https://github.com/vaadin/hilla/issues/1150

chore: address SonarCloud DoS-related issues

---

packages/ts/form/src/Validators.ts
packages/ts/form/test/Validators.test.ts

Closes #1150.
Depends on #1151.

fix: don't count minus sign in integer digits

---

packages/ts/form/src/index.ts
packages/ts/react-form/src/index.ts

feat: display React form value and validation state

---

packages/ts/form/src/BinderRoot.ts
packages/ts/form/src/Field.ts
packages/ts/react-form/src/index.ts
packages/ts/react-form/test/models.ts
packages/ts/react-form/test/useBinder.spec.tsx

fix(TypeScript): consistent validation updates in React forms

---

scripts/generator/generate.js
scripts/generator/src/creator.js
scripts/generator/templates/template-release-note-maintenance.md
scripts/generator/templates/template-release-note-prerelease.md
scripts/generator/templates/template-release-note.md

chore :  Add scripts to generate hilla release notes

---

scripts/generator/templates/template-release-note-maintenance.md
scripts/generator/templates/template-release-note-prerelease.md
scripts/generator/templates/template-release-note.md

chore: Update template-release-note.md

---

packages/ts/react-form/src/index.ts

feat: Add react form usage stats

---

lerna.json
package-lock.json
packages/java/endpoint/src/main/java/dev/hilla/EndpointController.java
packages/java/engine-core/src/main/java/dev/hilla/engine/GeneratorProcessor.java
packages/java/hilla-react/src/main/java/dev/hilla/HillaReactForm.java
packages/java/hilla/src/main/java/dev/hilla/HillaForm.java
packages/ts/form/package.json
packages/ts/form/src/index.ts
packages/ts/generator-typescript-cli/package.json
packages/ts/generator-typescript-core/package.json
packages/ts/generator-typescript-plugin-backbone/package.json
packages/ts/generator-typescript-plugin-barrel/package.json
packages/ts/generator-typescript-plugin-client/package.json
packages/ts/generator-typescript-plugin-model/package.json
packages/ts/generator-typescript-plugin-push/package.json
packages/ts/generator-typescript-utils/package.json
packages/ts/hilla-frontend/package.json
packages/ts/hilla-frontend/src/index.ts
packages/ts/react-form/package.json
packages/ts/react-form/src/index.ts

chore(release): npm version 2.2.0

---

packages/ts/react-grid/src/autogrid.tsx
packages/ts/react-grid/test/TestModels.ts
packages/ts/react-grid/test/autogrid.spec.tsx

Allows to customize the visible columns and their order in auto grid.
Closes https://github.com/vaadin/hilla/issues/1273
- Feature

feat: customize visible columns in auto grid

---

pom.xml

chore: Bump jacoco to 0.8.10

---

packages/ts/generator-typescript-plugin-model/src/EntityModelProcessor.ts
packages/ts/generator-typescript-plugin-model/src/ModelSchemaProcessor.ts
packages/ts/generator-typescript-plugin-model/src/utils.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormAnnotationsModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormArrayTypesModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormDataPrimitivesModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityHierarchyModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityIdModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEnumTypesModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormNonnullTypesModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormOptionalTypesModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormRecordTypesModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormTemporalTypesModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormValidationConstraintsModel.snap.ts

refactor(generator-typescript-plugin-model): update code according to #1252

---

packages/ts/react-form/src/index.ts
packages/ts/react-form/src/types.d.ts
packages/ts/react-form/test/models.ts
packages/ts/react-form/test/useForm.spec.tsx

refactor(react-form): update code according to #1252

---

packages/ts/form/src/BinderNode.ts
packages/ts/form/src/Models.ts
packages/ts/form/test/TestModels.ts
packages/ts/generator-typescript-plugin-model/src/ModelSchemaProcessor.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityIdModel.snap.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormValidationConstraintsModel.snap.ts
packages/ts/react-form/test/models.ts
packages/ts/react-grid/src/types/dev/hilla/mappedtypes/OrderModel.ts

Change model constructors to accept an optional options object instead of a variable number of validator arguments.

refactor: introduce model options

---

packages/ts/react-auth/package.json
packages/ts/react-auth/tsconfig.build.json
packages/ts/react-form/tsconfig.build.json
packages/ts/react-grid/tsconfig.build.json
scripts/build.ts

chore: Use the same build options for all modules

---

package-lock.json
packages/java/endpoint/src/main/java/dev/hilla/crud/CrudRepositoryService.java
packages/java/endpoint/src/main/java/dev/hilla/crud/CrudService.java
packages/java/tests/spring/react-grid-test/frontend/routes.tsx
packages/java/tests/spring/react-grid-test/frontend/views/AutoCrudView.tsx
packages/java/tests/spring/react-grid-test/frontend/views/AutoFormView.tsx
packages/java/tests/spring/react-grid-test/frontend/views/ReadOnlyGridSinglePropertyFilter.tsx
packages/java/tests/spring/react-grid-test/package-lock.json
packages/java/tests/spring/react-grid-test/package.json
packages/java/tests/spring/react-grid-test/src/main/java/dev/hilla/test/reactgrid/AbstractEntity.java
packages/java/tests/spring/react-grid-test/src/main/java/dev/hilla/test/reactgrid/Appointment.java
packages/java/tests/spring/react-grid-test/src/main/java/dev/hilla/test/reactgrid/AppointmentRepository.java
packages/java/tests/spring/react-grid-test/src/main/java/dev/hilla/test/reactgrid/AppointmentService.java
packages/java/tests/spring/react-grid-test/src/main/java/dev/hilla/test/reactgrid/package-info.java
packages/java/tests/spring/react-grid-test/src/test/java/dev/hilla/test/reactgrid/AutoFormViewIT.java
packages/ts/react-grid/package.json
packages/ts/react-grid/src/autoform-field.tsx
packages/ts/react-grid/src/autoform.tsx
packages/ts/react-grid/src/crud.ts
packages/ts/react-grid/src/index.ts
packages/ts/react-grid/test/autoform.spec.tsx
packages/ts/react-grid/test/test-models-and-services.ts

Can be used as
```
<ExperimentalAutoForm service={AppointmentService} model={AppointmentModel} />
```
to auto generate a form using AppointmentModel and allow submitting the result to the update method of the AppointmentService

feat: Auto Form component

---

packages/ts/react-grid/src/autogrid-column.tsx
packages/ts/react-grid/src/autogrid-columns.tsx
packages/ts/react-grid/src/autogrid-number-renderer.tsx
packages/ts/react-grid/src/autogrid.tsx
packages/ts/react-grid/src/header-column-context.tsx
packages/ts/react-grid/src/header-filter.tsx
packages/ts/react-grid/src/header-sorter.tsx
packages/ts/react-grid/src/utils.ts
packages/ts/react-grid/test/autogrid.spec.tsx
packages/ts/react-grid/test/test-models-and-services.ts

feat: Render number columns as right aligned numbers

---

.github/workflows/validation.yml
nx.json
package.json

Possible solution for build failures.

fix: disable nx cache for CI

---

packages/ts/form/src/BinderNode.ts
packages/ts/form/test/Binder.test.ts
packages/ts/form/test/TestModels.ts

* Create test for the issue
* fix(form): errors when defaultValue is set with array items
---------
(cherry picked from commit 6b0bfd3d6f4affc77cc036972e0fe05e76052c93)

fix(form): errors when defaultValue is set with array items (#1400)

---

packages/java/tests/spring/security/src/test/java/com/vaadin/flow/spring/fusionsecurity/SecurityIT.java

Partly rverts vaadin/hilla#1379

test: Re-enable tests removed with @PWA PR

---

packages/java/endpoint/src/main/java/dev/hilla/crud/CountService.java
packages/java/endpoint/src/main/java/dev/hilla/crud/CrudRepositoryService.java
packages/java/endpoint/src/main/java/dev/hilla/crud/CrudService.java
packages/java/endpoint/src/main/java/dev/hilla/crud/GetService.java
packages/java/endpoint/src/main/java/dev/hilla/crud/JpaFilterConverter.java
packages/java/endpoint/src/main/java/dev/hilla/crud/ListRepositoryService.java
packages/java/endpoint/src/test/java/dev/hilla/crud/CrudRepositoryServiceJpaTest.java
packages/java/endpoint/src/test/java/dev/hilla/crud/TestCrudRepositoryService.java

The get method is mandatory to implement, exists is default implemented and count is only implemented in the CrudRepositoryService
For #1404

feat: Add get/count/exists to CrudRepositoryService

---

packages/java/endpoint/src/main/java/dev/hilla/crud/filter/AndFilter.java
packages/java/endpoint/src/main/java/dev/hilla/crud/filter/OrFilter.java
packages/java/endpoint/src/main/java/dev/hilla/crud/filter/PropertyStringFilter.java
packages/ts/react-grid/test/autoform.spec.tsx
packages/ts/react-grid/test/autogrid.spec.tsx
packages/ts/react-grid/test/test-models-and-services.ts

test: Test that data provider is initially only called once

---

packages/java/tests/spring/react-grid-test/frontend/views/ReadOnlyGrid.tsx
packages/java/tests/spring/react-grid-test/src/test/java/dev/hilla/test/reactgrid/ReadOnlyGridIT.java
packages/ts/react-grid/src/autogrid-columns.tsx
packages/ts/react-grid/src/autogrid.tsx
packages/ts/react-grid/test/autogrid.spec.tsx

feat: Allow providing custom column options

---

packages/java/tests/spring/react-grid-test/frontend/views/ReadOnlyGrid.tsx
packages/java/tests/spring/react-grid-test/src/test/java/dev/hilla/test/reactgrid/AbstractGridTest.java
packages/java/tests/spring/react-grid-test/src/test/java/dev/hilla/test/reactgrid/ReadOnlyGridIT.java
packages/ts/react-grid/src/autogrid-renderers.tsx
packages/ts/react-grid/src/autogrid.tsx
packages/ts/react-grid/test/autogrid.spec.tsx

feat: Render row numbers if using rowNumbers

---

packages/java/tests/spring/react-grid-test/src/test/java/dev/hilla/test/reactgrid/AbstractGridTest.java
packages/java/tests/spring/react-grid-test/src/test/java/dev/hilla/test/reactgrid/AutoCrudViewIT.java
packages/ts/react-grid/src/autocrud.tsx
packages/ts/react-grid/src/autogrid-columns.tsx

Made ITs check browser logs for errors

fix: Include key for delete button

---

packages/java/endpoint/src/main/java/dev/hilla/crud/PropertyStringFilterSpecification.java
packages/java/tests/spring/react-grid-test/pom.xml
packages/java/tests/spring/react-grid-test/src/main/resources/data.sql
packages/java/tests/spring/react-grid-test/src/test/java/dev/hilla/test/reactgrid/ReadOnlyGridWithHeaderFilterIT.java
packages/ts/react-grid/src/autogrid-columns.tsx
packages/ts/react-grid/src/header-filter.tsx

Adds filtering to headers in date and time columns.
Closes #1285

feat(autogrid): add header filter for dates and times

---

packages/ts/generator-typescript-plugin-backbone/src/EntityProcessor.ts
packages/ts/generator-typescript-plugin-backbone/test/hierarchy-ref/HierarchyRef.json
packages/ts/generator-typescript-plugin-backbone/test/hierarchy-ref/HierarchyRef.spec.ts
packages/ts/generator-typescript-plugin-backbone/test/hierarchy-ref/fixtures/HierarchyRef.entity.snap.ts
packages/ts/generator-typescript-plugin-backbone/test/hierarchy-ref/fixtures/HierarchyRefEndpoint.snap.ts

fix(generator-typescript-plugin-backbone): correct superclass type ref in properties

---

packages/java/tests/spring/react-grid-test/src/main/java/dev/hilla/test/reactgrid/entityreferences/Department.java
packages/java/tests/spring/react-grid-test/src/main/java/dev/hilla/test/reactgrid/entityreferences/Employee.java
packages/java/tests/spring/react-grid-test/src/test/java/dev/hilla/test/reactgrid/GridWithEntityReferencesIT.java
packages/ts/react-grid/src/autogrid-columns.tsx
packages/ts/react-grid/src/property-info.ts

fix: Only render columns of known types by default

---

packages/ts/react-grid/src/autogrid-renderers.tsx
packages/ts/react-grid/test/autogrid.spec.tsx
packages/ts/react-grid/test/test-models-and-services.ts

Fixes rendering of nested properties when using auto-grid specific renderers.

fix: render nested properties in auto-grid

---

packages/ts/form/src/BinderNode.ts
packages/ts/form/test/Binder.test.ts
packages/ts/form/test/TestModels.ts

fix(form): iterating optional arrays immediately after initialization

---

packages/ts/form/test/Binder.test.ts
packages/ts/form/test/TestModels.ts

fix(form): iterating optional arrays immediately after initialization (#1493)

---

packages/java/endpoint/src/main/java/dev/hilla/EndpointControllerConfiguration.java
packages/java/endpoint/src/main/java/dev/hilla/push/PushConfigurer.java
packages/java/tests/spring/security-contextpath/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
packages/java/tests/spring/security-contextpath/src/main/resources/vaadin-featureflags.properties
packages/java/tests/spring/security-jwt/src/main/java/com/vaadin/flow/spring/fusionsecurityjwt/endpoints/BalanceEndpoint.java
packages/java/tests/spring/security-jwt/src/main/resources/vaadin-featureflags.properties
packages/java/tests/spring/security-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
packages/java/tests/spring/security-urlmapping/src/main/resources/vaadin-featureflags.properties
packages/java/tests/spring/security/frontend/views/private/private-view.ts
packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
packages/java/tests/spring/security/src/main/resources/vaadin-featureflags.properties
packages/java/tests/spring/security/src/test/java/com/vaadin/flow/spring/fusionsecurity/SecurityIT.java
packages/ts/frontend/src/FluxConnection.ts

fix(endpoint): support prefix and context path with reactive endpoints

---

packages/ts/react-crud/src/autoform.tsx
packages/ts/react-crud/test/FormController.ts
packages/ts/react-crud/test/autoform.spec.tsx

feat: Disable submit button when editing before any changes

---

.github/workflows/validation.yml
package.json

* chore: disable nx cache for all commands in CI
* chore(react-form): revert version change
* chore: bring build:nocache back for now
* chore: make build:nocache invoke build
---------
(cherry picked from commit f19036730b7c5cc94a13be257c917e1c829a0c75)

chore: disable nx cache for all commands in CI (#1554) (CP: 2.2)

---

.github/workflows/validation.yml
package.json

* chore: disable nx cache for all commands in CI
* chore(react-form): revert version change
* chore: bring build:nocache back for now
* chore: make build:nocache invoke build
---------
(cherry picked from commit f19036730b7c5cc94a13be257c917e1c829a0c75)

chore: disable nx cache for all commands in CI (#1554) (CP: 1.3)

---

package-lock.json
packages/ts/react-crud/package.json

Fixes https://github.com/vaadin/hilla/issues/1575

fix: bump react-crud dependencies

---

pom.xml

chore: update spring-boot to 3.1.5 (#1564) (CP: 2.3)

---

pom.xml

chore: update spring-boot to 3.1.5 (#1564) (CP: 2.2)

---

pom.xml

chore: update spring-boot to 3.1.5 (#1564) (CP: 2.1)

---

packages/ts/form/src/BinderNode.ts
packages/ts/form/test/Binder.test.ts

Fixes #1565
(cherry picked from commit 1b2b3e02a9d2cd67d692a49f89a74d4fcb31eedc)

fix(form): skip child nodes whose defaultValue is undefined (#1583) (CP: 2.3)

---

.github/workflows/validation.yml
package.json

* chore: disable nx cache for all commands in CI
* chore(react-form): revert version change
* chore: bring build:nocache back for now
* chore: make build:nocache invoke build
---------
(cherry picked from commit f19036730b7c5cc94a13be257c917e1c829a0c75)

chore: disable nx cache for all commands in CI (#1554) (CP: 2.1)

---

packages/ts/form/src/BinderNode.ts
packages/ts/form/test/Binder.test.ts

Fixes #1565
(cherry picked from commit 1b2b3e02a9d2cd67d692a49f89a74d4fcb31eedc)

fix(form): skip child nodes whose defaultValue is undefined (#1583) (CP: main)

---

packages/java/tests/spring/react-grid-test/package.json
packages/java/tests/spring/react-grid-test/src/test/java/dev/hilla/test/reactgrid/AbstractGridTest.java
packages/ts/react-crud/src/property-info.ts
packages/ts/react-crud/test/test-models-and-services.ts

Add support for properties in parent classes

---

packages/ts/generator-typescript-plugin-model/src/ModelSchemaProcessor.ts
packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityModel.snap.ts

fix(generator-typescript-plugin-model): update ObjectModel generics

---

packages/java/endpoint/src/main/java/dev/hilla/crud/PropertyStringFilterSpecification.java
packages/java/endpoint/src/test/java/dev/hilla/crud/FilterTest.java
packages/java/endpoint/src/test/java/dev/hilla/crud/TestObject.java

Manual CherryPick for #1616 to 2.3 branch.

fix: allow filtering float properties (CP: #1616)

---

packages/ts/react-crud/src/autocrud.tsx
packages/ts/react-crud/src/autoform.tsx
packages/ts/react-crud/src/shared/types.ts
packages/ts/react-crud/src/util.ts
packages/ts/react-crud/test/autocrud.spec.tsx
packages/ts/react-crud/test/autoform.spec.tsx

Add id,style,className properties to AutoCrud and AutoForm
Fixes #1640

feat(autocrud): Add id, style, className properties to AutoCrud and AutoForm 

---

packages/java/endpoint/src/main/java/dev/hilla/EndpointControllerConfiguration.java
packages/java/endpoint/src/main/java/dev/hilla/push/PushConfigurer.java
packages/java/tests/spring/security-contextpath/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
packages/java/tests/spring/security-contextpath/src/main/resources/vaadin-featureflags.properties
packages/java/tests/spring/security-jwt/src/main/java/com/vaadin/flow/spring/fusionsecurityjwt/endpoints/BalanceEndpoint.java
packages/java/tests/spring/security-jwt/src/main/resources/vaadin-featureflags.properties
packages/java/tests/spring/security-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
packages/java/tests/spring/security-urlmapping/src/main/resources/vaadin-featureflags.properties
packages/java/tests/spring/security/frontend/views/private/private-view.ts
packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
packages/java/tests/spring/security/src/main/resources/vaadin-featureflags.properties
packages/java/tests/spring/security/src/test/java/com/vaadin/flow/spring/fusionsecurity/SecurityIT.java
packages/ts/frontend/src/FluxConnection.ts
packages/ts/frontend/test/FluxConnection.test.ts

Fixes #1354
(cherry picked from commit ebe67654f70703c70028230634cef56884914fb2)

fix(endpoint): support prefix and context path with reactive endpoints (#1543) (CP: 2.3)

---

packages/java/endpoint/src/main/java/dev/hilla/EndpointControllerConfiguration.java
packages/java/endpoint/src/main/java/dev/hilla/push/PushConfigurer.java
packages/java/tests/spring/security-contextpath/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
packages/java/tests/spring/security-contextpath/src/main/resources/vaadin-featureflags.properties
packages/java/tests/spring/security-jwt/src/main/java/com/vaadin/flow/spring/fusionsecurityjwt/endpoints/BalanceEndpoint.java
packages/java/tests/spring/security-jwt/src/main/resources/vaadin-featureflags.properties
packages/java/tests/spring/security-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
packages/java/tests/spring/security-urlmapping/src/main/resources/vaadin-featureflags.properties
packages/java/tests/spring/security/frontend/views/private/private-view.ts
packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
packages/java/tests/spring/security/src/main/resources/vaadin-featureflags.properties
packages/java/tests/spring/security/src/test/java/com/vaadin/flow/spring/fusionsecurity/SecurityIT.java
packages/ts/frontend/src/FluxConnection.ts
packages/ts/frontend/test/FluxConnection.test.ts

Fixes #1354
(cherry picked from commit ebe67654f70703c70028230634cef56884914fb2)

fix(endpoint): support prefix and context path with reactive endpoints (#1543) (CP: 2.2)

---

packages/java/tests/spring/react-grid-test/frontend/views/AutoCrudView.tsx
packages/java/tests/spring/react-grid-test/frontend/views/AutoFormView.tsx
packages/ts/react-crud/src/autocrud.tsx
packages/ts/react-crud/src/autoform.tsx
packages/ts/react-crud/test/autocrud.spec.tsx
packages/ts/react-crud/test/autoform.spec.tsx

refactor: remove experimental from auto crud and form

---

package-lock.json
packages/ts/form/package.json
packages/ts/form/src/Binder.ts
packages/ts/form/src/BinderNode.ts
packages/ts/form/src/BinderRoot.ts
packages/ts/form/src/types.d.ts
packages/ts/form/test/Validation.test.ts

fix(form): use correct call for interpolateMessageCallback

---

packages/java/tests/spring/react-grid-test/frontend/views/AutoFormView.tsx
packages/ts/react-crud/src/autoform.tsx

Expose event types for auto form so they can be imported by the application.

refactor: expose auto form event types

---

package-lock.json
packages/ts/react-crud/src/autoform-field.tsx
packages/ts/react-crud/test/FormController.ts
packages/ts/react-crud/test/autoform.spec.tsx
packages/ts/react-crud/test/autogrid.spec.tsx
packages/ts/react-crud/test/test-models-and-services.ts

Update to `package-lock.json` is necessary to avoid using an old version of React Components.
Closes #1624.

feat(autoform): add `DateTimeField`

---

pom.xml

chore: upgrade vaadin-parent to 2.2.1

---

packages/ts/react-crud/src/autoform-field.tsx
packages/ts/react-crud/test/autoform.spec.tsx
packages/ts/react-crud/test/autogrid.spec.tsx
packages/ts/react-crud/test/test-models-and-services.ts

fix(react-crud): render nested properties in auto form

---

packages/ts/react-crud/src/autoform-field.tsx
packages/ts/react-crud/test/autoform.spec.tsx
packages/ts/react-crud/test/autogrid.spec.tsx
packages/ts/react-crud/test/test-models-and-services.ts

(cherry picked from commit d7d0050dc428125f59872ca0b1b85d76f1bd6dcc)

fix(react-crud): render nested properties in auto form (#1776) (CP: 2.4)

---

.github/workflows/validation.yml

Revert "chore: do not rerun failing tests and hide issues (#1353)"
This reverts commit 2b1ea6d0954587197cf11518163842d761eb5f9f.

chore: add rerun for IT tests

---

packages/ts/react-crud/src/autoform.tsx
packages/ts/react-crud/test/autoform.spec.tsx

feat(autoform): submit form on Enter key press

---

packages/ts/react-crud/src/autogrid-columns.tsx
packages/ts/react-crud/src/header-filter.tsx
packages/ts/react-crud/test/autogrid.spec.tsx

Add custom placeholder, debounce, and minimum length properties to column options for grid filters.
Fixes #1492

feat(autgrid): Add custom placeholder, debounce and minimum length to filters

---

packages/java/endpoint/src/main/java/dev/hilla/crud/ListService.java

fix: add NonNull to ListService.list

---

pom.xml

deps: bump copilot to 24.3.4

---

packages/java/endpoint/src/main/java/com/vaadin/hilla/EndpointInvoker.java
packages/java/endpoint/src/main/java/com/vaadin/hilla/exception/EndpointValidationException.java
packages/ts/form/src/BinderRoot.ts
packages/ts/form/src/Validation.ts
packages/ts/form/test/Validation.test.ts
packages/ts/frontend/src/EndpointErrors.ts
packages/ts/react-crud/src/autoform.tsx
packages/ts/react-crud/test/autoform.spec.tsx

Add form-level validation errors from validators with no property.
Fixes #1674

feat: add form level validation error from entity level validator

---

pom.xml

chore: Flow bump to 24.3.3 and Copilot bump to 24.3.5

---

pom.xml

Copilot version update to 24.3.6

chore: Copilot version update to 24.3.6

---

packages/ts/frontend/src/Connect.ts
packages/ts/frontend/src/FluxConnection.ts
packages/ts/frontend/test/Connect.test.ts

Manual cherry-pick of #1959 due to different source code.

feat: allow to amend Atmosphere configuration (#1959) (CP: 1.4)

---

package-lock.json
packages/java/tests/spring/endpoints discovery/package-lock.json
packages/java/tests/spring/endpoints-contextpath/package-lock.json
packages/java/tests/spring/endpoints-custom-client/package-lock.json
packages/java/tests/spring/endpoints-latest-java/package-lock.json
packages/java/tests/spring/endpoints/package-lock.json
packages/java/tests/spring/react-grid-test/package-lock.json
packages/java/tests/spring/security-contextpath/package-lock.json
packages/java/tests/spring/security-jwt/package-lock.json
packages/java/tests/spring/security-urlmapping/package-lock.json
packages/java/tests/spring/security/package-lock.json

chore(2.5): also update lock files

---

packages/java/tests/csrf-context/pom.xml

related commits in flow 
https://github.com/vaadin/flow/pull/18665
https://github.com/vaadin/flow/pull/18703

fix: update configuration as reactRouterEnabled has been renamed

---

.github/workflows/validation.yml

add 2.4 into workflow branch list

---

package-lock.json

Align package-lock.json after https://github.com/vaadin/hilla/pull/2124

chore: align package-lock

---

package-lock.json
packages/java/gradle-plugin/pom.xml
packages/java/tests/spring/react-signals/package-lock.json

Removes the leftover reference to hilla-plugin-base dependency

chore: remove hilla-plugin-base reference from gradle plugin

---

scripts/prepare/templates/components/react/package.json

Earlier this was put into the devDependencies.

fix: move hilla-file-router to dependencies

---

package-lock.json
packages/ts/hilla-file-router/package.json
packages/ts/hilla-file-router/src/runtime/toReactRouter.ts
packages/ts/hilla-file-router/src/runtime/useViewConfig.ts

fix(file-router): remove extra peer dependency to react-router

---

packages/java/tests/spring/react-signals/src/test/java/com/vaadin/hilla/test/BasicSignalIT.java

That test fails often on TeamCity. If this works, similar changes may be required in the CRUD IT module.

chore(test): change the signal IT so that is't hopefully less flaky

---

.github/workflows/validation.yml
package-lock.json

Also, remove the `edited` from the list of events
that triggers a build e.g. when the title or the
description of a PR changes.

feat: upload gradle-plugin validation build outputs

---

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java
packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteExtractionIndexHtmlRequestListener.java
packages/java/endpoint/src/main/java/com/vaadin/hilla/route/records/AvailableViewInfo.java
packages/java/endpoint/src/main/java/com/vaadin/hilla/route/records/ClientViewConfig.java
packages/java/endpoint/src/main/java/com/vaadin/hilla/route/records/ClientViewMenuConfig.java
packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteExtractionIndexHtmlRequestListenerTest.java
packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views.json

fix(file-router): update Java code to be compliant with the TS code

---

packages/ts/hilla-file-router/package.json
packages/ts/hilla-file-router/src/runtime/createMenuItems.ts
packages/ts/hilla-file-router/src/shared/internal.d.ts
packages/ts/hilla-file-router/src/types.d.ts
packages/ts/hilla-file-router/src/vite-plugin/createViewConfigJson.ts
packages/ts/hilla-file-router/test/runtime/createMenuItems.spec.ts
packages/ts/hilla-file-router/test/utils.tsx
packages/ts/hilla-file-router/test/vite-plugin/collectRoutesFromFS.spec.ts
scripts/build.ts

Resolves #2157.
Resolves #2156.

refactor(file-router): remove or extract non-public API elements

---

.mocharc.json

https://github.com/vaadin/hilla/pull/967

test(TypeScript): prevent hangups of TypeScrpt tests on CI (CP : 1.5)

---

packages/ts/file-router/src/vite-plugin/collectRoutesFromFS.ts
packages/ts/file-router/test/utils.tsx
packages/ts/file-router/test/vite-plugin/createRoutesFromMeta.spec.ts

feat(fs-router): change dollar to at in special filenames

---

packages/ts/react-auth/src/ProtectedRoute.tsx

This is to be in sync how Flow had to be done

chore: Change ProtectedRoute export to a type property

---

.github/workflows/validation.yml
packages/java/tests/spring/native/pom.xml
packages/java/tests/spring/pom.xml
scripts/prepare/index.ts

This reverts commit 5b39484d272c4ec5737af1a14ffe25c6e7342970.

chore: Revert "chore: fix ts build script (#2407)"

---

.gitignore
packages/java/tests/gradle/single-module-tests/build.gradle
packages/java/tests/gradle/single-module-tests/gradle.properties
packages/java/tests/gradle/single-module/build.gradle
packages/java/tests/gradle/single-module/gradle.properties
packages/java/tests/pom.xml
packages/java/tests/spring/react-grid-test/pom.xml
packages/java/tests/spring/react-signals/pom.xml
scripts/prepare/config.ts
scripts/prepare/index.ts

chore: remove Lumo / Material class copies (#2106) (CP: 24.4)

---

scripts/hooks/stats.js

This removes the unnecessary console log in stats.js

chore: remove redundant console log

---

.gitignore
package-lock.json
packages/ts/file-router/package.json
packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts
packages/ts/file-router/src/vite-plugin/collectRoutesFromFS.ts
packages/ts/file-router/src/vite-plugin/utils.ts
packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx
packages/ts/file-router/test/vite-plugin/collectRoutesFromFS.spec.ts
packages/ts/file-router/test/vite-plugin/createViewConfigJson.spec.ts
packages/ts/file-router/test/vite-plugin/generateRuntimeFiles.spec.ts
packages/ts/generator-cli/package.json
packages/ts/generator-core/package.json
packages/ts/generator-plugin-backbone/package.json
packages/ts/generator-plugin-barrel/package.json
packages/ts/generator-plugin-client/package.json
packages/ts/generator-plugin-model/package.json
packages/ts/generator-plugin-push/package.json
packages/ts/generator-plugin-subtypes/package.json
packages/ts/generator-utils/package.json
packages/ts/react-signals/package.json

refactor: adjust route analysis & transformation (#2443, #2448) (CP: 24.4)

---

packages/ts/file-router/src/vite-plugin/createRoutesFromMeta.ts
packages/ts/file-router/src/vite-plugin/createViewConfigJson.ts
packages/ts/file-router/test/utils.tsx
packages/ts/file-router/test/vite-plugin/createRoutesFromMeta.spec.ts
packages/ts/file-router/test/vite-plugin/createViewConfigJson.spec.ts

fix(file-router): support config below view

---

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java
packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java
packages/java/endpoint/src/test/resources/META-INF/VAADIN/file-routes.json
packages/ts/file-router/src/vite-plugin/createViewConfigJson.ts
packages/ts/file-router/test/utils.tsx
packages/ts/file-router/test/vite-plugin/createViewConfigJson.spec.ts

(cherry picked from commit 9f087d13983b50fc6851cdd4ecfdb58a69b9bebc)

refactor(file-router): make route with non-null children detected as a layout (#2493) (CP: 24.4)

---

packages/ts/lit-form/src/Validators.ts
packages/ts/lit-form/test/Validators.test.ts

fix: replace validator/isNumeric with a simple NaN & Finite check

---

packages/ts/react-form/src/index.ts
packages/ts/react-form/test/models.ts
packages/ts/react-form/test/useForm.spec.tsx

(cherry picked from commit a2c5f28f1827487311eb60714e2882b4086a1dcd)

fix(binder): update form when array values change (#2497) (CP: 2.5)

---

packages/ts/frontend/src/Connect.ts
packages/ts/frontend/src/FluxConnection.ts
packages/ts/frontend/test/FluxConnection.test.ts
packages/ts/react-signals/test/FullStackSignal.spec.tsx
packages/ts/react-signals/test/utils.ts

feat: add onConnectionStateChange callback for flux subscription

---

packages/java/maven-plugin/pom.xml

Aligns with Flow maven plugin version.

chore: bump maven-plugin-plugin to 3.15.0

---

package-lock.json
packages/ts/file-router/package.json
packages/ts/react-auth/package.json
packages/ts/react-signals/package.json

* chore(react-signals): remove unnecessary dependency
* chore(ts): update react-router-dom version
---------
(cherry picked from commit 37ba04c707178099182fe380815d52e7675862cd)

chore(ts): update react-router-dom dependency version (#2904) (CP: 24.5)

---

packages/java/endpoint/src/main/java/com/vaadin/hilla/EndpointInvoker.java

chore: fix java doc

---

karma.config.cjs
packages/ts/react-crud/test/autoform.spec.tsx

This reverts commit c7d1b1a7e2906b7dde4c3c92c9a2821aad696406.

test: Fix viewport size for test for real

---

package-lock.json
package.json
packages/ts/react-signals/package.json

Adds support for React 19 and fixes fast refresh issues

chore: Bump preact (#3023) (CP: 24.6)

---

packages/java/endpoint/src/main/java/com/vaadin/hilla/push/PushConfigurer.java
packages/java/endpoint/src/main/java/com/vaadin/hilla/push/PushEndpoint.java
packages/java/tests/spring/react-grid-test/src/main/java/com/vaadin/hilla/test/reactgrid/Application.java

fix: fix dependency conflict for ObjectMapper in PushEndpoint

---

packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/EndpointExposedPlugin.java

Revert "chore: Expose methods from Flow crud classes to browser callables"

---

packages/java/engine-core/src/main/java/com/vaadin/hilla/engine/AotBrowserCallableFinder.java
packages/java/engine-core/src/main/java/com/vaadin/hilla/engine/EngineConfiguration.java
packages/java/gradle-plugin/src/main/kotlin/com/vaadin/hilla/gradle/plugin/HillaPlugin.kt

fix: take Gradle's multiple classes dirs into account

---

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUtil.java
packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUtilTest.java

fix(endpoint): update file routes security per every request in dev mode

---

package-lock.json
packages/ts/file-router/package.json
packages/ts/frontend/package.json
packages/ts/generator-cli/package.json
packages/ts/generator-core/package.json
packages/ts/generator-plugin-backbone/package.json
packages/ts/generator-plugin-barrel/package.json
packages/ts/generator-plugin-client/package.json
packages/ts/generator-plugin-model/package.json
packages/ts/generator-plugin-push/package.json
packages/ts/generator-plugin-signals/package.json
packages/ts/generator-plugin-subtypes/package.json
packages/ts/generator-plugin-transfertypes/package.json
packages/ts/generator-utils/package.json
packages/ts/lit-form/package.json
packages/ts/models/package.json
packages/ts/react-auth/package.json
packages/ts/react-crud/package.json
packages/ts/react-form/package.json
packages/ts/react-i18n/package.json
packages/ts/react-signals/package.json

This reverts commit bce593a6ab96201e14d498366a5cdf33a9cf1ee3.

Revert "chore(release): npm version 24.7.0-beta2"

---

packages/ts/react-crud/src/autocrud.tsx
packages/ts/react-crud/test/autocrud.spec.tsx

Fixes https://github.com/vaadin/hilla/issues/3334.

fix(crud): always include wrapper div, even when no New button

---

packages/ts/react-crud/src/autogrid.tsx
packages/ts/react-crud/test/GridController.ts
packages/ts/react-crud/test/autogrid.spec.tsx
packages/ts/react-crud/test/grid-test-utils.js

feat: bring empty state handling of Grid to AutoGrid

---

pom.xml

chore: upgrade vaadin-parent to 3.0.0

---

packages/java/gradle-plugin/build.gradle

test(gradle-plugin): adjust functional test implementation dependencies

---

packages/java/endpoint/pom.xml

chore: drop android-json dependency

---

packages/java/tests/spring/react-grid-test/src/test/java/com/vaadin/hilla/test/reactgrid/ReadOnlyGridWithHeaderFilterIT.java
packages/ts/react-crud/test/ConfirmDialogController.tsx
packages/ts/react-crud/test/SelectController.ts
packages/ts/react-crud/test/autogrid.spec.tsx

Change how an item in a select is found using TestBench to fix error in test.

fix(test): simplify item selection logic

---

packages/java/endpoint/pom.xml
packages/java/endpoint/src/main/java/com/vaadin/hilla/EndpointControllerConfiguration.java
packages/java/endpoint/src/main/java/com/vaadin/hilla/crud/ListRepositoryService.java
packages/java/endpoint/src/test/java/com/vaadin/hilla/EndpointControllerConfigurationTest.java
packages/java/endpoint/src/test/java/com/vaadin/hilla/EndpointControllerTest.java
packages/java/endpoint/src/test/java/com/vaadin/hilla/EndpointInvokerTest.java
packages/java/endpoint/src/test/java/com/vaadin/hilla/ServletContextTestSetup.java
packages/java/endpoint/src/test/java/com/vaadin/hilla/crud/CrudRepositoryServiceJpaTest.java
packages/java/endpoint/src/test/java/com/vaadin/hilla/crud/CrudRepositoryServiceTest.java
packages/java/endpoint/src/test/java/com/vaadin/hilla/push/PushMessageHandlerTest.java
packages/java/engine-core/src/main/java/com/vaadin/hilla/engine/AotBrowserCallableFinder.java
packages/java/gradle-plugin/build.gradle
packages/java/gradle-plugin/src/functionalTest/kotlin/com/vaadin/hilla/gradle/plugin/AbstractGradleTest.kt
packages/java/gradle-plugin/src/functionalTest/kotlin/com/vaadin/hilla/gradle/plugin/SingleModuleTest.kt
packages/java/gradle-plugin/src/functionalTest/kotlin/com/vaadin/hilla/gradle/plugin/TestUtils.kt
packages/java/parser-jvm-plugin-backbone/src/test/resources/com/vaadin/hilla/parser/plugins/backbone/generics/openapi.json
packages/java/tests/gradle/kotlin-gradle-test/build.gradle
packages/java/tests/gradle/kotlin-gradle-test/settings.gradle
packages/java/tests/spring/endpoints/src/main/java/com/vaadin/flow/connect/LegacySecurityConfig.java
packages/java/tests/spring/endpoints/src/main/java/com/vaadin/flow/connect/SecurityConfig.java
packages/java/tests/spring/react-signals/src/main/java/com/vaadin/hilla/test/signals/Application.java
packages/java/tests/spring/react-signals/src/main/java/com/vaadin/hilla/test/signals/security/LegacySecurityConfiguration.java
packages/java/tests/spring/react-signals/src/main/java/com/vaadin/hilla/test/signals/security/SecurityConfiguration.java
packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/LegacySecurityConfig.java
packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/SecurityConfig.java
pom.xml

Perform the upgrade to Spring Boot 4 again.
Closes #3672.

chore: upgrade Spring Boot to 4.0.0-M1

---

packages/java/parser-jvm-plugin-backbone/src/test/resources/com/vaadin/hilla/parser/plugins/backbone/generics/openapi.json
pom.xml

chore: bump spring-boot to 3.5.4

---

packages/ts/file-router/src/runtime/configuration-builder/createFallbackTransformer.ts
packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx

fix(file-router): restore original fallback logic

---

pom.xml

chore: upgrade javaparser.core to 3.27.1
