client/.eslintrc, client/packages/client-common/src/ConnectionIndicator.ts, client/packages/client-common/src/index.ts, client/packages/client-fusion/src/Authentication.ts, client/packages/client-fusion/src/form/Binder.ts, client/packages/client-fusion/src/form/BinderNode.ts, client/packages/client-fusion/src/form/Field.ts, client/packages/client-fusion/src/form/Models.ts, client/packages/client-fusion/src/form/Validation.ts, client/packages/client-fusion/src/form/Validators.ts, client/packages/client-fusion/src/form/index.ts, client/packages/client-fusion/src/index.ts
1. Updated all the import statements to use `.js` extension, including those for `valiidator` package.
2. Disabled `import/no-unresolved` ESLint rule as it does not play well with ES modules (see comment).
Fixes #71
- Internal change
=> fix: add .js extension to all imports

.github/workflows/frontend-release.yml, frontend/scripts/bump.sh
- Rename GITHUB_TOKEN -> RELEASE_TOKEN in case GitHub overwrites the variable by a different value
- Make bash script falling on any command error
=> chore(frontend): more fixes in order to make the release runnable

frontend/scripts/bump.sh
Delete protection on the release push to avoid "Protected branch update failed" error. Also add `catch` to restore the branch protection in case the release fails.
=> chore(frontend): delete branch protection on release

.github/workflows/frontend-release.yml, frontend/scripts/bump/update-package-versions.js
- Update `version` in `package.json` for packages.
- Re-build version after bumping to get correct versions in built code
- Use correct publishing for Lerna
=> chore(frontend): make publishing more correct

frontend/packages/form/src/Models.ts, frontend/packages/form/test/Field.test.ts, frontend/packages/form/test/Model.test.ts
Related to https://github.com/vaadin/spring/issues/904.
Porting the fix in https://github.com/vaadin/flow/pull/11169.
=> fix: NumberModel should read empty string as undefined

frontend/.eslintrc, frontend/README.md, frontend/packages/form/package.json, frontend/packages/form/test/Field.test.ts, frontend/packages/form/test/Validation.test.ts, frontend/packages/form/test/tsconfig.json, frontend/packages/form/tsconfig.json, frontend/packages/fusion-frontend/package.json, frontend/packages/fusion-frontend/test/Authentication.test.ts, frontend/packages/fusion-frontend/test/Connect.test.ts, frontend/packages/fusion-frontend/test/SpringCsrfTestUtils.test.ts, frontend/packages/fusion-frontend/test/tsconfig.json, frontend/packages/fusion-frontend/tsconfig.json, frontend/tsconfig.json
Enable linting and type checking for test sources. Get rid of all current lint issues (also warnings). Fix command in readme and few minor refactorings.
chore(readme): fix command in readme
- The main `package.json` is under the `frontend` directory and not in repository root. Fix the related `cd` command in the readme.
chore: improve IDE linting config for tests
- Add tsconfigs to the test directories to prevent linting errors in VS Code related to global mocha methods like describe being undefined. The test sources need to be included in some tsconfig for the TS integration in the IDE to use e.g. the mocha type declarations in the context of the test files.
chore: fix syntax error in `tsconfig.json`
chore: enable linting and type checking for test sources
test: improve cookie handling …
=> chore: minor improvements, mainly linting fixes

packages/ts/form/src/Validators.ts, packages/ts/form/test/Validators.test.ts
According to https://beanvalidation.org/2.0-jsr380/spec/#builtinconstraints-size, both `min` and `max` parameters of the `Size` constraint are optional, therefore it is possible to declare empty `@Size` without arguments. However, the corresponding `Size` model always requied an object argument.
This change makes the `Size` form validator argument optional, and enables using `new Size()` model validator without arguments corresponding to the empty `@Size` annotation in Java.
=> fix(form): support empty Size validator

packages/ts/form/src/Binder.ts, packages/ts/form/src/Validation.ts, packages/ts/form/test/TestModels.ts, packages/ts/form/test/Validation.test.ts
Add API for enabling interpolation of validation messages (e.g. for localization purposes) via a static property interpolateMessageCallback on Binder.
Fixes #127
=> feat: validation message interpolation

packages/ts/generator-typescript-plugin-backbone/src/EndpointProcessor.ts, packages/ts/generator-typescript-plugin-backbone/src/EntityProcessor.ts, packages/ts/generator-typescript-plugin-backbone/src/TypeSchemaProcessor.ts, packages/ts/generator-typescript-utils/src/dependencies/PathManager.ts
Removes the necessity to use `#cwd` property
=> refactor(java/parser-jvm-utils): use global relativeTo approach for PathManager

packages/ts/fusion-frontend/src/CsrfUtils.ts, packages/ts/fusion-frontend/test/Connect.test.ts, packages/ts/fusion-frontend/test/SpringCsrfTestUtils.test.ts
When Spring CSRF is disabled, it brings meta tags with string undefined (`'undefined'`) to the index.html page which results in CSRF check malfuction
Fixes #185
=> fix: handle spring csrf as string undefined in meta tags

packages/java/maven-plugin/pom.xml
renaming so that it doesn't conflict with the [hilla-maven-plugin](https://github.com/vaadin/platform/tree/master/hilla-maven-plugin) in the platform repo
=> refactor: rename hilla-maven-plugin to generator-maven-plugin

packages/ts/generator-typescript-cli/package.json, packages/ts/generator-typescript-plugin-backbone/package.json, packages/ts/generator-typescript-plugin-barrel/package.json, packages/ts/generator-typescript-plugin-client/package.json, packages/ts/generator-typescript-plugin-model/package.json, scripts/bump/exec.sh, scripts/bump/package-update.js
Fixes the issue of Lerna when it cannot update the version of the monorepo package mentioned in `peerDependencies` instead of `dependencies`: lerna/lerna#1575
=> chore: add ts release script to fix the lerna peer dependencies issue

packages/ts/form/src/Models.ts, packages/ts/form/test/Model.test.ts, scripts/node/esbuild.js
The default string to boolean conversion is not suitable, since all strings (including "false") are converted to true. This patch follows the convention used by [validator.js](https://github.com/validatorjs/validator.js/blob/master/src/lib/isBoolean.js) to avoid inconsistencies.
Fixes #177
=> fix: boolean model converts "true" and "false" to their boolean equivalents

packages/ts/form/src/Models.ts, packages/ts/form/test/Model.test.ts
* Boolean model should accept some values as true
* chore: update node hooks
(cherry picked from commit 14bfc1fb168bac9fb6cca58e856da7e8cfbee049)
=> fix: boolean model converts "true" and "false" to their boolean equivalents (#406) (CP: 1.0)

packages/ts/form/src/Binder.ts, packages/ts/form/src/Field.ts, packages/ts/form/test/Field.test.ts
Fixes #151
Enables using models in the field strategy. The `<vaadin-combo-box>` strategy
uses `value` property when binding with models of primitive types
(boolean, string, number) and `selectedItem` for object and array types.
=> feat(form): support vaadin-combo-box string value / use model in field strategy

packages/ts/hilla-frontend/src/FluxConnection.ts
This avoids conflict with the VaadinServlet when it is bound to /VAADIN/*
=> fix!: Use /HILLA/push instead of /VAADIN/... for the push endpoint

packages/ts/form/src/Binder.ts, packages/ts/form/src/Field.ts, packages/ts/form/test/Field.test.ts
* feat(form): support vaadin-combo-box string value / use model in field strategy
Fixes #151
Enables using models in the field strategy. The `<vaadin-combo-box>` strategy
uses `value` property when binding with models of primitive types
(boolean, string, number) and `selectedItem` for object and array types.
* test(form): add dynamic strategy selection test
(cherry picked from commit ae22e76a6e424bc0832f1138ebb2b97139547115)
=> feat(form): support vaadin-combo-box string value / use model in field strategy (#421) (CP: 1.1)

packages/ts/hilla-frontend/src/Connect.ts, packages/ts/hilla-frontend/src/FluxConnection.ts, packages/ts/hilla-frontend/test/FluxConnection.test.ts
When the context becomes inactive, the subscription is cancelled
Fixes #400
=> feat: Allow binding a subscription to a context

packages/ts/hilla-frontend/src/Connect.ts, packages/ts/hilla-frontend/src/FluxConnection.ts, packages/ts/hilla-frontend/test/FluxConnection.test.ts
* fix: properly clean up on subscription cancel()
* feat: Allow binding a subscription to a context
When the context becomes inactive, the subscription is cancelled
Fixes #400
(cherry picked from commit b37f89a4b52babc2ce7dd1999fa55ced9061c08f)
=> feat: Allow binding a subscription to a context (#420) (CP: 1.1)

packages/ts/hilla-frontend/test/FluxConnection.test.ts
* fix: properly clean up on subscription cancel()
* Reduce duplication
(cherry picked from commit 78ac1ca232fad462ba09e09f73d5679017d38602)
=> fix: properly clean up on subscription cancel() (#419) (CP: 1.1)

packages/ts/hilla-frontend/mocks/socket.io-client.ts, packages/ts/hilla-frontend/src/Connect.ts, packages/ts/hilla-frontend/src/FluxConnection.ts, packages/ts/hilla-frontend/src/index.ts, packages/ts/hilla-frontend/test/Connect.test.ts, packages/ts/hilla-frontend/test/FluxConnection.test.ts
* feat: Emit state change events from FluxConnection
These can be used to implement reconnect logic for Fluxes but also to update the UI to indicate that server pushes are not being received
* Use EventTarget
* Extend EventTarget
* Merge with an interface
(cherry picked from commit 134dbb5481ffb84cfaa32625912b4f2488ebf7a6)
=> feat: Emit state change events from FluxConnection (#405) (CP: 1.1)

packages/ts/hilla-frontend/src/Connect.ts, packages/ts/hilla-frontend/test/Connect.test.ts
As a developer, I want to be able to cancel endpoint requests by using `AbortController`. This feature adds support for an optional call parameter, which allows to specify an `AbortSignal`. The endpoint generator is modified in the Flow repository to allow developers to add the signal to their calls if needed.
Fixes #169
=> feat: allow developers to cancel endpoint requests

package-lock.json, package.json, web-test-runner.config.js
As currently web tests cannot be run on TeamCity as Chrome is needed. By switching to Puppeteer, they work there too. That seems to have no consequences running them elsewhere as before, but that's still quite a change as far as tests are concerned.
Fixes #436
=> Use Puppeteer as browser for web tests to allow them to run on TeamCity

packages/ts/hilla-frontend/src/Connect.ts
To conform with thanges in vaadin/flow#13878
=> chore: rename the `endpointRequestInit` param to simply `init`

.github/workflows/validation.yml
Adding a pro license to the GitHub Validation workflow to allow tests using the Test Bench to pass.
Fixes #463
=> fix(ci): add a pro license to use the test bench

packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoReflectionModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoSourceModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoReflectionModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoSourceModel.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/PackageInfoModelTests.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/pack/Foo.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/pack/PackageInfoModelSample.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/pack/package-info.java
Adds `PackageInfoModel` to the list of core models.
Annotations provided by the ClassGraph `PackageInfo#getAnnotations` return `null` for `getClassInfo` call which should get information of their original class. For now it is better to use string names.
=> feat(parser-jvm-core): add PackageInfoModel

packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/core/AssociationMap.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/core/SignatureInfo.java, packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/EndpointProcessor.java, packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/EntityProcessor.java, packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/SchemaProcessor.java, packages/java/parser-jvm-plugin-model/src/main/java/dev/hilla/parser/plugins/model/ValidationConstraint.java, packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullProcessor.java
Add an `SignatureInfo` structure to `AssociationMap` that allows extracting the base of the signature: either a method, a field or a parameter. This addition allows getting the `PackageInfo` for the signature which was impossible before.
=> refactor(parser-jvm-core): add SignatureInfo to the AssociationMap

packages/java/engine-runtime/src/main/java/dev/hilla/internal/TaskGenerateHillaImpl.java, packages/java/maven-plugin/pom.xml
The `engine-maven-plugin` is configured to use `hilla` as prefix for goal invocation. The `TaskGenerateHillaImpl` is modified to use that prefix too.
Closes #493
=> chore: use `hilla` instead of `engine` as Maven prefix

package-lock.json
As Flow tries to upgrade Lit to 2.3.0, some tests fail due to version mismatch with peer dependencies in the root. Allowing those versions to update fixes those errors.
=> fix: update Lit version in root package-lock.json

packages/java/endpoint/src/main/java/dev/hilla/generator/typescript/CodeGenerator.java, packages/java/endpoint/src/test/resources/dev/hilla/generator/endpoints/flux/expected-FluxTestEndpoint.ts
Change the source-based generator code to never return `undefined` for endpoint methods that call `client.subscribe`.
Note: this fix is an API change.
Fixes #484
=> fix: remove the `undefined` return type for Flux endpoint methods

packages/ts/generator-typescript-cli/src/index.ts, packages/ts/generator-typescript-core/src/Generator.ts, packages/ts/generator-typescript-core/src/SharedStorage.d.ts, packages/ts/generator-typescript-plugin-backbone/src/EndpointMethodOperationProcessor.ts, packages/ts/generator-typescript-plugin-backbone/src/EndpointProcessor.ts, packages/ts/generator-typescript-plugin-backbone/src/index.ts, packages/ts/generator-typescript-plugin-backbone/test/custom-client/CustomClient.json, packages/ts/generator-typescript-plugin-backbone/test/custom-client/CustomClient.spec.ts, packages/ts/generator-typescript-plugin-backbone/test/custom-client/connect-client.ts, packages/ts/generator-typescript-plugin-backbone/test/custom-client/fixtures/CustomClientEndpoint.snap.ts, packages/ts/generator-typescript-plugin-backbone/test/utils/common.ts, packages/ts/generator-typescript-plugin-barrel/test/basic/BasicBarrel.spec.ts, packages/ts/generator-typescript-plugin-client/src/index.ts, packages/ts/generator-typescript-plugin-client/test/basic/BasicClient.spec.ts, packages/ts/generator-typescript-plugin-model/src/index.ts, packages/ts/generator-typescript-plugin-model/test/model/Model.spec.ts, packages/ts/generator-typescript-plugin-push/src/index.ts, packages/ts/generator-typescript-plugin-push/test/utils/common.ts
Adds a check to verify if a file named `frontend/connect-client.ts` exists, just like in the single-module generator.
Fixes #485
=> fix(engine): add support for custom connect client

packages/java/endpoint/src/main/java/dev/hilla/generator/GeneratorType.java, packages/java/endpoint/src/main/java/dev/hilla/generator/OpenAPIObjectGenerator.java, packages/java/endpoint/src/test/java/dev/hilla/generator/endpoints/nonnullable/NonNullableEndpoint.java, packages/java/endpoint/src/test/resources/dev/hilla/generator/endpoints/nonnullable/expected-NonNullableEndpoint.ts
Fix how the check is performed to restore the old behavior and always honors `additionalAnnotations`.
Fixes #523
=> Fix non-null check

packages/java/engine-runtime/src/main/java/dev/hilla/internal/TaskGenerateHillaImpl.java, packages/java/engine-runtime/src/test/java/dev/hilla/internal/TaskGenerateHillaImplTest.java
Uses `mvn.cmd` instead of `mvn`
Fixes #507
=> fix: run `generate` on Windows

packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/AnnotationMatcher.java
For now, you cannot specify annotation for `NonnullPlugin` using the `pom.xml`:
```xml
<plugin>
<groupId>dev.hilla</groupId>
<artifactId>hilla-maven-plugin</artifactId>
<version>${hilla.version}</version>
<configuration>
<parser>
<plugins>
<use>
<plugin>
<name>dev.hilla.parser.plugins.nonnull.NonnullPlugin</name>
<configuration
implementation="dev.hilla.parser.plugins.nonnull.NonnullPluginConfig">
<use>
<annotation>
<name>com.example.application.Nonnull</name>
<makesNullable>false</makesNullable>
<score>30</score>
</annotation>
</use>
</configuration>
</plugin>
</use>
</plugins>
</parser>
</configuration>
...
</plugin>
```
It will fail because `AnnotationMatcher` does not have a default constructor.
This PR fixes the issue.
=> fix(parser-jvm-plugin-nonnull): add default constructor to make AnnotationMatcher usable in Maven config

packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/core/NodeDependencies.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/core/NodePath.java, packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/BackbonePlugin.java, packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/JSONPlugin.java, packages/java/parser-jvm-plugin-backbone/src/main/java/module-info.java, packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/json/Endpoint.java, packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/json/JSONAnnotationsEndpoint.java, packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/json/JSONAnnotationsTest.java, packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/json/JsonIgnoredType.java, packages/java/parser-jvm-plugin-backbone/src/test/resources/dev/hilla/parser/plugins/backbone/json/openapi.json, packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java, pom.xml
To make the multi-module engine more compatible with the source-based generator, this PR excludes fields that have the `JsonIgnore` annotation, fields whose type has the `JsonIgnoreType` annotation, and also fields that are listed in the `JsonIgnoreProperties` annotation, if present.
In passing, two small corrections are made in the main `pom.xml`, feel free to revert that commit if too out of scope.
Fixes #440 
Fixes #297 (for the multi-module engine)
=> fix(parser): ignore fields annotated with JsonIgnore

packages/java/endpoint/pom.xml, packages/java/engine-runtime/pom.xml, packages/java/maven-plugin/pom.xml, packages/java/parser-jvm-core/pom.xml, packages/java/parser-jvm-plugin-backbone/pom.xml, packages/java/parser-jvm-plugin-model/pom.xml, packages/java/parser-jvm-plugin-nonnull/pom.xml, packages/java/parser-jvm-plugin-transfertypes/pom.xml, packages/java/parser-jvm-test-utils/pom.xml, packages/java/parser-jvm-utils/pom.xml, packages/java/runtime-plugin-transfertypes/pom.xml, packages/java/tests/csrf-context/pom.xml, packages/java/tests/csrf/pom.xml, packages/java/tests/pom.xml, packages/java/tests/spring/endpoints-custom-client/pom.xml, packages/java/tests/spring/endpoints-latest-java/pom.xml, packages/java/tests/spring/endpoints/pom.xml, packages/java/tests/spring/pom.xml, packages/java/tests/spring/security-contextpath/pom.xml, packages/java/tests/spring/security-jwt/pom.xml, packages/java/tests/spring/security-urlmapping/pom.xml, packages/java/tests/spring/security/pom.xml, pom.xml
This PR sets `2.0-SNAPSHOT` as the current POM version for the `main` branch.
Part of https://github.com/vaadin/flow/issues/14785
=> chore: set the POM version to 2.0-SNAPSHOT

packages/java/tests/spring/endpoints/src/main/java/com/vaadin/flow/connect/SecurityConfig.java, packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/SecurityConfig.java
This PR refactors some of the integration tests to get them extended from `VaadinWebSecurity` which is officially advised for use instead of the deprecated `VaadinWebSecurityConfigurerAdapter` class.
This change is required for #599 to prevent a circular reference that otherwise emerges when using Spring Security 6.
Part of https://github.com/vaadin/flow/issues/14785
=> test: use VaadinWebSecurity instead of deprecated VaadinWebSecurityConfigurerAdapter

pom.xml
Spring Boot 3 RC1 uses SLF4J 2
=> chore!: Upgrade to SLF4J 2.0

packages/java/endpoint/src/main/java/dev/hilla/push/SocketIoWebsocketConfigurer.java
old fusion-endpoint had trailing slash
=> fix(endpoint): websocket path matching is not matching because of trailing slash

.github/workflows/validation.yml
github action offers a feature that asking the team member to trigger the build.
=> chore: remove the permission checking step

packages/java/endpoint/src/main/resources/dev/hilla/generator/EntityModelTemplate.mustache, packages/java/endpoint/src/test/resources/dev/hilla/generator/tsmodel/expected-TsFormEndpoint.ts, packages/ts/form/test/TestModels.ts, packages/ts/generator-typescript-plugin-model/src/EntityModelProcessor.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormAnnotationsModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormArrayTypesModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormDataPrimitivesModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityHierarchyModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityIdModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormNonnullTypesModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormOptionalTypesModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormRecordTypesModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormTemporalTypesModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormValidationConstraintsModel.snap.ts
Fixes #655
When omitting the declare keyword, Vite v3.2.3 produces an empty
property in the JS output. Adding `declare` makes it explicit that it is
not expected in JS.
=> fix: generate declare keyword for createEmptyValue methods

.github/workflows/validation.yml
This removes package-based matrix variables from the GitHub Actions Validation workflow. The aim is to reduce parallel quota pressure and save on the container start / stop overhead.
=> build: simplify build matrix

packages/java/tests/pom.xml
A new dependency seems to be required by webdrivermanager v5.3.2,
introduced in https://github.com/vaadin/flow/pull/15734
=> test(java/tests): add required webdrivermanager dependency

packages/java/endpoint/src/main/java/dev/hilla/push/PushConfigurer.java
Fixes the problem
```
[ERROR] dev.hilla.push.PushConfigurer.EmbeddedAtmosphereInitializer has private access in dev.hilla.push.PushConfigurer /.../spring-aot/main/sources/dev/hilla/push/PushConfigurer__BeanDefinitions.java 52:53
```
=> fix: Make push work with native compile

pom.xml
seems TB in hilla 1.3 should be 8.2.0 instead of 8.1.x https://github.com/vaadin/platform/blob/23.3/versions.json#L677
=> chore: align TB version in hilla 1.3

packages/ts/generator-typescript-plugin-model/src/EntityModelProcessor.ts, packages/ts/generator-typescript-plugin-model/src/ModelSchemaProcessor.ts, packages/ts/generator-typescript-plugin-model/test/model/Model.json, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormAnnotationsModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormArrayTypesModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormDataPrimitivesModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityHierarchyModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityIdModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormOptionalTypesModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormRecordTypesModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormTemporalTypesModel.snap.ts, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormValidationConstraintsModel.snap.ts
Parser no longer emits the list of required fields for an entity, but model generator was relying on it. The implementation changes to use `nullable` as in the entity generation.
Fixes #790.
=> fix(engine): change how model checks for nullable fields

packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoReflectionModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoSourceModel.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/PackageInfoModelTests.java, packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java, packages/java/parser-jvm-plugin-nonnull/src/test/java/dev/hilla/parser/plugins/nonnull/nonnullapi/NonNullApiEndpoint.java, packages/java/parser-jvm-plugin-nonnull/src/test/java/dev/hilla/parser/plugins/nonnull/nonnullapi/subpackage/SubPackageDependency.java, packages/java/parser-jvm-plugin-nonnull/src/test/resources/dev/hilla/parser/plugins/nonnull/nonnullapi/openapi.json
Modifies the NonnullPlugin to apply `@NonNullApi` annotation from ancestor packages.
Fixes #788
=> fix(engine): let NonNullPlugin find `NonNullApi` annotation on parent packages

packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoReflectionModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoSourceModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoReflectionModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoSourceModel.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/Dummy.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/ClassInfoModelTests.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/PackageInfoModelTests.java, packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java
Move the API to the ClassInfoModel where we have the good class loader. Finding ancestors is still a "best effort" since packages start existing when a class is loaded from them (see test for an example).
Fixes #816
=> fix: use classloader from current class to find packages

packages/ts/form/src/Validators.ts, packages/ts/form/test/Validators.test.ts
Fix the NotBlank validator to trim whitespace in line with it's jakarta.validator equivalent.
Fixes #833
=> Trim whitespace before checking length of string. Fixes #833

packages/ts/form/src/BinderNode.ts, packages/ts/form/src/Field.ts, packages/ts/form/src/Validators.ts, packages/ts/form/src/Validity.ts, packages/ts/form/test/Binder.test.ts, packages/ts/form/test/TestModels.ts, packages/ts/form/test/Validation.test.ts, packages/ts/form/test/Validators.test.ts
Fixes #702
In some form element binding cases (notably, for user-typed value in
`<vaadin-date-picker>`), the binder validation additionally verify
the value from the element using the element's own internal validation
defined by the `checkValidity()` result and the `validity` property.
This change implements such verification, so that a value invalidated
by the element's internal validation is considered invalid by the
binder.
=> feat(form): consider errors from HTML and Vaadin components built-in validation

.github/workflows/validation.yml, .lintstagedrc.cjs
This PR is in preparation for #884, which will not pass until this one is merged.
=> fix: allow to create modules with spaces in names

packages/java/engine-runtime/src/test/java/dev/hilla/internal/NodeTasksEndpointTest.java, packages/java/parser-jvm-utils/pom.xml, pom.xml
After https://github.com/vaadin/flow/pull/16653 is merged, 
the com.vaadin.flow.server.frontend.Options class does not 
have the withDevBundleBuild method, and the new name is 
withBundleBuild.
=> test: make test code compatible with flow latest changes

packages/java/engine-core/src/main/java/dev/hilla/engine/commandrunner/CommandRunner.java
When commands like `mvn` or `node` are run, they are first tested with dummy arguments like `-v`. The output of those command is not significant, yet it appears in the logs.  This PR hides that text.
=> fix: hide output of test commands

.github/workflows/validation.yml
This is a temporary change to make the builds pass 
until the Gradle tests extracted to a parallel
validation build.
=> chore: increase build timeout to 25 minutes

packages/java/endpoint/src/main/java/dev/hilla/EndpointInvoker.java
The `EndpointInvoker` gets the Spring `ApplicationContext` as constructor parameter, so we can use the Spring Validator Bean instead of the explicit one.
Closes #964.
=> feat: use Spring Validator when available

packages/java/hilla-plugin-base/src/main/java/dev/hilla/plugin/base/InitFileExtractor.java
Add those files to the React-related list, as the ones provided by Flow are Lit-based.
=> fix: scaffold `types.d.ts` and `vite.config.ts` in React

packages/java/gradle-plugin/src/functionalTest/kotlin/dev/hilla/gradle/plugin/SingleModuleTest.kt, packages/java/gradle-plugin/src/main/kotlin/dev/hilla/gradle/plugin/EngineProjectExtension.kt, packages/java/gradle-plugin/src/main/kotlin/dev/hilla/gradle/plugin/HillaPlugin.kt, packages/java/tests/gradle/single-module-tests/build.gradle, packages/java/tests/gradle/single-module-tests/settings.gradle, packages/java/tests/gradle/single-module-tests/src/test/java/dev/hilla/gradle/plugin/test/ProductionBuildFunctionalIT.java, packages/java/tests/gradle/single-module/build.gradle, packages/java/tests/gradle/single-module/settings.gradle
This enables the possibility of using the `hilla` extension to  
set the `productionMode` either in the `build.gradle`:
```
hilla {
productionMode = true
}
```
or via command-line arguments:
```
./gradlew -Philla.productionMode=true build
```
Fixes #984
=> feat: enable setting productionMode through hilla instead of using vaadin extension

packages/java/maven-plugin/src/main/java/dev/hilla/maven/CleanFrontendMojo.java, packages/java/maven-plugin/src/main/java/dev/hilla/maven/ConvertPolymerMojo.java, packages/java/maven-plugin/src/main/java/dev/hilla/maven/FrontendDanceMojo.java
In #929 the necessary goals from flow-maven-plugin is adopted 
into hilla-maven-plugin directly. But, just to prevent introducin a
breaking change in a minor release, the following goals are added 
to the plugin and marked as `deprecated` as there is no actual use 
for them in a Hilla project:
- convert-polymer
- clean-frontend
- dance
Fixes #988
=> chore: add missing maven goals for backward compatibility

packages/java/engine-core/src/main/java/dev/hilla/engine/ParserConfiguration.java, packages/java/engine-core/src/test/java/dev/hilla/engine/EngineConfigurationTest.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/core/PluginConfiguration.java, packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/AnnotationMatcher.java, packages/java/parser-jvm-plugin-nonnull/src/test/java/dev/hilla/parser/plugins/nonnull/basic/BasicTest.java
* Add default constructor to AnnotationMatcher to enable maven initialize it properly
* Enable PluginConfiguration to be serialized properly into configuration file 
Fixes #923
=> fix: enable overriding the plugins

.github/workflows/validation.yml
Refine the branches to trigger the validation build instead of 1.1 and 1.0.
=> chore: refine branches to trigger validation build

packages/java/engine-core/src/main/java/dev/hilla/engine/commandrunner/GradleRunner.java, packages/java/engine-core/src/test/java/dev/hilla/engine/commandrunner/GradleRunnerTest.java
This adds the support for having the Gradle Build file in Kotlin (build.gradle.kts)
Fixes #1039
=> fix: create CommandRunner instance if build.gradle.kts was available

packages/java/gradle-plugin/build.gradle
This change fixes the documentation and source VCS URLs in the Gradle Plugin description.
=> chore(gradle-plugin): fix URLs in Gradle Plugin metadata

packages/java/plugin-base/src/main/java/dev/hilla/plugin/base/HillaAppInitUtility.java, packages/java/plugin-base/src/test/java/dev/hilla/plugin/base/HillaAppInitUtilityTest.java
This changes the package extraction approach for the class 
annotated with `@SpringBootApplication` by excluding all type
of java comments (single and multi-line), javadocs, and string 
literals, and then tries to extract the package declaration.  
Fixes #1048
=> fix: fix package extraction failure when package declaration is not first line

packages/java/gradle-plugin/src/main/kotlin/dev/hilla/gradle/plugin/HillaBuildFrontendTask.kt, packages/java/gradle-plugin/src/main/kotlin/dev/hilla/gradle/plugin/HillaPlugin.kt, packages/java/maven-plugin/src/main/java/dev/hilla/maven/BuildFrontendMojo.java
Skip cleaning of frontend
files that did not exist
before bundle build.
Depends on vaadin/flow#17080
=> fix: Do not clean frontend files

.github/workflows/validation.yml
It allows that we can have dots in artifactId so as we can add `dev.hilla.gradle.plugin` in #1087
This should be merged before #1087
=> chore: fix regexp to allow dots in artifactId

packages/java/engine-core/src/main/java/dev/hilla/engine/commandrunner/GradleRunner.java
This PR fixes Gradle test failure on Windows
=> fix(jvm-parser): use gradle.exe as executable as well

packages/java/endpoint/src/main/java/dev/hilla/push/PushConfigurer.java
This is a partial revert for the change in #1103
to just let the DefaultBroadcaster be used since
it is able to broadcast asynchronously by using
an ExecutorService to broadcast the messages to
the suspended responses while SimpleBroadcaster
is blocked by the current thread.
=> fix: set atmosphere's default broadcaster back to default

packages/ts/generator-typescript-plugin-backbone/src/EntityProcessor.ts, packages/ts/generator-typescript-plugin-backbone/test/no-properties/NoProperties.json, packages/ts/generator-typescript-plugin-backbone/test/no-properties/NoProperties.spec.ts, packages/ts/generator-typescript-plugin-backbone/test/no-properties/fixtures/CoreEntity.snap.ts, packages/ts/generator-typescript-plugin-backbone/test/no-properties/fixtures/ExampleEntity.snap.ts, packages/ts/generator-typescript-plugin-backbone/test/no-properties/fixtures/NoPropertiesEndpoint.snap.ts
While it's unlikely to want to use entities with no properties in endpoints, they can exist up in the class hierarchy as supertypes and the generator wants to deal with them.
This PR adds a simple fix to generate empty entities.
Fixes #1105
=> fix: accept entities with no properties

packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoReflectionModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoSourceModel.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/ClassInfoModelTests.java, packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java, packages/java/parser-jvm-plugin-nonnull/src/test/java/dev/hilla/parser/plugins/nonnull/nonnullapi/NonNullApiEndpoint.java, packages/java/parser-jvm-plugin-nonnull/src/test/java/dev/hilla/parser/plugins/nonnull/nonnullapi/subpackage/SubPackageDependency.java, packages/java/parser-jvm-plugin-nonnull/src/test/resources/dev/hilla/parser/plugins/nonnull/nonnullapi/openapi.json
Fixes #921
Applying NonNullApi on subpackages is convenient, but it proved to be not reliable due to how packages work in Java.
We found contradictory indications in the Spring documentation, but it looks reasonable to conform to the general Java rule.
=> fix: make NonNullApi only work on own package

packages/ts/form/src/BinderRoot.ts, packages/ts/react-form/src/index.ts, packages/ts/react-form/test/useBinder.spec.tsx
Updates the references for the `onChange` and `onSubmit` callbacks in the `BinderRoot` whenever the `useBinder` hook is called again.
Fixes https://github.com/vaadin/hilla/issues/1193
- Bugfix
=> fix(react-form): update callback references on useBinder hook call

packages/ts/react-form/src/index.ts, packages/ts/react-form/test/useForm.spec.tsx
Following the internal DX feedback and discussions, the folowing APIs and types are renamed here:
- `useBinder` → `useForm`
- `useBinderNode` → `useFormPart`
- `BinderControls` → `UseFormResult`
- `BinderNodeControls` → `UseFormPartResult`
=> refactor(react-form): rename API entrypoints

scripts/prepare.sh
Json files generation happen before the version setting to maven modules, so using the `project.version` from root pom is not a ideal way here.
=> chore: use npm module version for generation script [skip ci]

packages/ts/form/src/Validation.ts, packages/ts/form/test/Validation.test.ts
Adds error handling to validator executions, so that binder validation and update can still complete in case a validator unexpectedly throw an error.
- Bugfix
=> fix(form): gracefully handle validator throwing an error

packages/ts/hilla-frontend/src/Authentication.ts, packages/ts/hilla-frontend/src/Connect.ts, packages/ts/hilla-frontend/test/Connect.test.ts
Fixes #1154.
There is a small API change since now the `Response` type is expected in middleware, but this shouldn't break any existing code since that's the only type that the middleware could deal with anyway.
=> fix!: use explicit `Response` type in Middleware

packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoReflectionModel.java, packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/generics/ConcreteType.java, packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/generics/GenericInterface.java, packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/generics/ImplementInterfaceEndpoint.java, packages/java/parser-jvm-plugin-backbone/src/test/resources/dev/hilla/parser/plugins/backbone/generics/openapi.json
When implementing a generic interface, compliant methods are generated as synthetic ones.
This PR filters them out, otherwise those methods are randomly picked as choices when parsing.
Fixes #1210
=> fix(parser-jvm-core): Filter synthetic methods

packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/EndpointExposedPlugin.java, packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/MethodPlugin.java, packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/genericsuperclassmethods/Endpoint.java, packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/genericsuperclassmethods/EndpointExposed.java, packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/genericsuperclassmethods/GenericSuperClass.java, packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/genericsuperclassmethods/GenericSuperClassLong.java, packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/genericsuperclassmethods/GenericSuperClassMethodsTest.java, packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/genericsuperclassmethods/GenericSuperClassString.java, packages/java/parser-jvm-plugin-backbone/src/test/resources/dev/hilla/parser/plugins/backbone/genericsuperclassmethods/openapi.json
When a method is defined in the super class, the definition needs to be duplicated for each implementing class so that generics can be set separately for each instance
Fixes #1214
=> fix(parser-jvm-plugin-backbone): Properly expand generic types

.eslintrc, packages/ts/form/src/BinderNode.ts, packages/ts/react-form/src/index.ts, packages/ts/react-form/test/models.ts, packages/ts/react-form/test/useForm.spec.tsx
Currently optional models have a value of `undefined` when being bound to a field. This can cause validators such as `Size` to fail, as they expect a string value. 
This change enforces initialization of models as soon as they are bound to a field, so that a `StringModel` for example gets a value of an empty string as soon as it is bound to a field.
Fixes https://github.com/vaadin/hilla/issues/1197
- Bugfix
=> fix(react-form): force initialize optional models when binding to field

packages/java/hilla-react/pom.xml, packages/java/hilla/pom.xml
If a newer antrun plugin is available, the build fails with "You are using 'tasks' which has been removed from the maven-antrun-plugin. Please use 'target' and refer to the >>Major Version Upgrade to version 3.0.0<< on the plugin site"
<!-- PLEASE READ AND FOLLO
=> chore: Fix build

packages/ts/form/src/BinderRoot.ts, packages/ts/form/test/Binder.test.ts, packages/ts/react-form/src/index.ts
This is convenient as you can "bind" to a selection in grid - either a value or undefined if unselected
=> feat: Allow clearing the form by reading undefined or null

.github/workflows/validation.yml
=> chore: Run validation on 2.2 instead of 2.0

packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoReflectionModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoSourceModel.java, packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/FieldInfoModel.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/dependency/DependencyTests.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/ClassInfoModelTests.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/jackson/JacksonPropertyModelTests.java, packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/PropertyPlugin.java, packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/jackson/JacksonTest.java, packages/java/parser-jvm-plugin-backbone/src/test/resources/dev/hilla/parser/plugins/backbone/enumtype/openapi.json, packages/java/parser-jvm-plugin-backbone/src/test/resources/dev/hilla/parser/plugins/backbone/jackson/openapi.json, packages/java/parser-jvm-plugin-transfertypes/src/test/resources/dev/hilla/parser/plugins/transfertypes/pageable/bare/openapi.json, packages/java/parser-jvm-plugin-transfertypes/src/test/resources/dev/hilla/parser/plugins/transfertypes/pageable/basic/openapi.json
The natural order is... natural. This allows using the TS model to generate e.g. grid columns in the same order the properties are in the bean
=> fix: Do not sort class fields

packages/ts/react-grid/.prettierignore
Git commit hook prettifies files that are ignored by ESLint in `react-grid`. Let's create a similar config for Prettier.
=> chore: ignore same files as eslint when prettifying

packages/java/endpoint/src/main/java/dev/hilla/internal/hotswap/HotSwapServiceInitializer.java, packages/java/endpoint/src/test/java/dev/hilla/internal/hotswap/HotSwapServiceInitializerTest.java
If the liveReload is not null, but none
of the backends (SpringBootDevTools,
JRebel, or HotSwapAgent) was not
configured, the endpoint hotswap service
should not be enabled.
=> fix: hotswap should not get enabled when liveReloadBackend is null

packages/java/endpoint/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
In order for the dev.hilla.ApplicationContextProvider to be loaded and initialized in Hilla applications from classpath, it should be listed in the imports of springboot auto-configurations. Otherwise, depending classes such as EndpointCodeGenerator will not function properly.
=> fix: add ApplicationContextProvider in springboot AutoConfiguration imports

packages/java/parser-jvm-plugin-model/pom.xml, packages/java/parser-jvm-plugin-model/src/main/java/dev/hilla/parser/plugins/model/Annotation.java, packages/java/parser-jvm-plugin-model/src/main/java/dev/hilla/parser/plugins/model/ModelPlugin.java, packages/java/parser-jvm-plugin-model/src/test/java/dev/hilla/parser/model/test/helpers/TestHelper.java, packages/java/parser-jvm-plugin-model/src/test/java/dev/hilla/parser/plugins/model/Endpoint.java, packages/java/parser-jvm-plugin-model/src/test/java/dev/hilla/parser/plugins/model/EndpointExposed.java, packages/java/parser-jvm-plugin-model/src/test/java/dev/hilla/parser/plugins/model/annotations/AnnotationsEndpoint.java, packages/java/parser-jvm-plugin-model/src/test/java/dev/hilla/parser/plugins/model/annotations/AnnotationsTest.java, packages/java/parser-jvm-plugin-model/src/test/java/dev/hilla/parser/plugins/model/validation/ValidationEndpoint.java, packages/java/parser-jvm-plugin-model/src/test/java/dev/hilla/parser/plugins/model/validation/ValidationTest.java, packages/java/parser-jvm-plugin-model/src/test/resources/dev/hilla/parser/plugins/model/annotations/openapi.json
Adds annotations for properties to the schema. The annotations are filtered by an include list, which currently only includes `jakarta.persistence.Id` and `jakarta.persistence.Version`.
Part of https://github.com/vaadin/hilla/issues/1266
=> feat: add annotations to schema

packages/java/parser-jvm-plugin-model/src/main/java/dev/hilla/parser/plugins/model/ModelPlugin.java, packages/java/parser-jvm-plugin-model/src/test/java/dev/hilla/parser/plugins/model/javatypes/JavaTypeEndpoint.java, packages/java/parser-jvm-plugin-model/src/test/java/dev/hilla/parser/plugins/model/javatypes/JavaTypeTest.java, packages/java/parser-jvm-plugin-model/src/test/resources/dev/hilla/parser/plugins/model/annotations/openapi.json, packages/java/parser-jvm-plugin-model/src/test/resources/dev/hilla/parser/plugins/model/javatypes/openapi.json, packages/java/parser-jvm-plugin-model/src/test/resources/dev/hilla/parser/plugins/model/validation/openapi.json
Adds the fully qualified Java type name to the generated `openapi.json`. This is part of getting the Java type information into the generated models in order to use them for CRUD features like choosing a proper column renderer or form field type.
Part of https://github.com/vaadin/hilla/issues/1271
=> feat: add java type to parser

packages/ts/generator-typescript-plugin-subtypes/test/push-type/fixtures/AddEventModel.snap.ts
https://github.com/vaadin/hilla/pull/1336 got auto-merged even if failing. This PR fixes the modified model in test.
=> chore: update test model

packages/ts/generator-typescript-plugin-backbone/src/EntityProcessor.ts, packages/ts/generator-typescript-plugin-model/src/EntityModelProcessor.ts
Some OpenAPI definitions are not compatible with those plugins, yet they should not trigger an error. Another plugin can deal with, like the subtypes one.
Closes #1350.
=> chore: relax error level in backbone and model plugins

packages/ts/react-auth/src/ProtectedRoute.tsx, packages/ts/react-auth/src/useAuth.tsx, packages/ts/react-auth/test/ProtectedRoute.spec.tsx, packages/ts/react-auth/test/useAuth.spec.tsx
Working on updating the starters it was rather odd that the auth state contains a user object with two dozen properties that might exist, but you can't really be sure unless you double check in the backend. This proposes an alternative that would allow providing a custom user type to the auth module. It also does some minor improvements to how the context works, so that the auth provider doesn't require passing a value, and the `useAuth` hook is actually the hook that devs can call to get the auth state from the context.
To start with, apps would have some module like `frontend/util/auth.ts` that configures the auth module to use a specific user type:
```ts
import { configureAuth } from "@hilla/react-auth";
import { UserEndpoint } from "Frontend/generated/endpoints";
// Configure auth to …
```
=> feat(react-auth): allow customizing user type

packages/java/endpoint/src/main/java/dev/hilla/EndpointInvoker.java, packages/java/endpoint/src/main/java/dev/hilla/EndpointUtil.java, packages/java/tests/spring/security/frontend/routes.ts, packages/java/tests/spring/security/frontend/views/public/proxied-service-test-view.ts, packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/SecurityConfig.java, packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/service/GreetingService.java, packages/java/tests/spring/security/src/test/java/com/vaadin/flow/spring/fusionsecurity/SecurityIT.java
If a service class that is annotated with `@Endpoint` or `@BrowserCallable` is proxied at runtime e.g. by
annotating it by `@Transactional`, the invoked endpoint at runtime would be proxied subclass of the actual endpoint. In this case, resolving the target for access checking should consider resolving the original endpoint class not the runtime proxy object.
=> fix: add support for proxied services as endpoints

packages/ts/react-grid/src/autogrid.tsx, packages/ts/react-grid/src/utils.ts, packages/ts/react-grid/test/autogrid.spec.tsx, packages/ts/react-grid/test/test-models-and-services.ts
Use Java annotations instead of property names for determining which columns to exclude.
Closes https://github.com/vaadin/hilla/issues/1266
=> refactor: use annotations for excluding properties

packages/java/endpoint/pom.xml, pom.xml
Tests that use the static instance variable of EndpointCodeGenerator cannot run in parallel with any other test. It seems that annotating these tests with @NotThreadSafe does not help as the setup part is still run in parallel and this is the problematic part.
=> test: Do not run endpoint tests in parallel

.github/workflows/validation.yml
Do not build test files, do not build javadoc, do not build the gradle plugin
=> chore: Minimize the base build

packages/ts/form/src/BinderNode.ts, packages/ts/form/src/Validation.ts, packages/ts/form/test/Binder.test.ts, packages/ts/form/test/TestModels.ts
In forms that have arrays, when `binder.defaultValue` contains array items (for example, when initialized using `.read()`), having deep bindings with array item object was causing an error. The reason is that the binder failed to change the user-defined default value for the array item when initializing deep objects inside the item.
This change makes the binder maintain the user-defined array-item default value applying the same approach to arrays as when initializing optional keys in objects. When it needs to initialize a deep object inside the array item, it automatically changes the value and defaultValue of the array item at the same time, so that both get the deep keys in this case.
Fixes #1294
=> fix(form): errors when defaultValue is set with array items

package-lock.json, package.json, packages/ts/form/package.json, packages/ts/frontend/package.json, packages/ts/generator-typescript-core/package.json, packages/ts/generator-typescript-plugin-backbone/package.json, packages/ts/generator-typescript-plugin-barrel/package.json, packages/ts/generator-typescript-plugin-client/package.json, packages/ts/generator-typescript-plugin-model/package.json, packages/ts/generator-typescript-plugin-push/package.json, packages/ts/generator-typescript-plugin-subtypes/package.json, packages/ts/generator-typescript-utils/package.json, packages/ts/react-auth/package.json, packages/ts/react-form/package.json, packages/ts/react-grid/package.json
This should fix problems with multiple TypeScript versions being mixed and TypeScript 5.2 installed in node_modules/@hilla/something/node_modules
=> fix: Use the same Typescript version as Flow

packages/ts/form/src/Binder.ts, packages/ts/form/src/Models.ts, packages/ts/form/test/TestModels.ts
Fixes TypeScript type inference for `binder.model` that was broken after #1252
=> fix(form): inference for generic binder.model type

.github/workflows/validation.yml
- builds of external PRs are early stopped, so as a project owner can review it before running validation.
- set read permissions to the build
- stop concurrent builds in the same branch if there are newer changes to validate
=> chore: check contributor permissions before running validation

packages/java/parser-jvm-plugin-model/src/main/java/dev/hilla/parser/plugins/model/ModelPlugin.java, packages/java/parser-jvm-plugin-model/src/test/java/dev/hilla/parser/plugins/model/annotations/AnnotationsEndpoint.java, packages/java/parser-jvm-plugin-model/src/test/resources/dev/hilla/parser/plugins/model/annotations/openapi.json, packages/ts/generator-typescript-plugin-model/src/ModelSchemaProcessor.ts, packages/ts/generator-typescript-plugin-model/test/model/Model.json, packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityMetadataModel.snap.ts
Add support for generating JPA relationship annotations. Also fixes generator to use the property schema for generating metadata when handling nested models.
=> feat: generate JPA relationship annotations

packages/ts/react-grid/src/date-formatter.ts, packages/ts/react-grid/test/date-formatter.spec.ts
Implements locale-specific parsing of dates, as a pre-requisite for being able to parse and format dates in date pickers in the same format that is used for rendering cells (https://github.com/vaadin/hilla/pull/1442). The implementation is loosely based on that of the Flow component. The basic idea is to format an example date with a specific locale, and use that to extract a Regex pattern that allows to parse a date in that format in reverse. 
This implementation is far from perfect: there is no leniency for additional or missing whitespace, it does not handle dates before 0 (mostly because Intl.DateTimeFormat doesn't), only works with arabic numerals etc. 
Using a library like `date-fns` would help with some of those issues. But it doesn't solve figuring out which date format to use …
=> feat: implement locale specific date parser

packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/core/Parser.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/security/Endpoint.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/security/EndpointExposed.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/security/classlevel/EndpointExposedAndSecurityAnnotationTest.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/security/classlevel/ParentEndpoint.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/security/classlevel/SomeEndpoint.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/security/methodlevel/AnotherEndpoint.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/security/methodlevel/EndpointExposedMethodAndSecurityAnnotationTest.java, packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/core/security/methodlevel/ParentEndpoint.java
Throw a ParserException if an `@EndpointExposed` class contains AccessControl annotations.
Fixes #1314
=> feat: throw if an @EndpointExposed class contains AccessControl annotations

packages/java/endpoint/src/main/java/dev/hilla/crud/JpaFilterConverter.java, packages/java/endpoint/src/main/java/dev/hilla/crud/PropertyStringFilterSpecification.java, packages/java/endpoint/src/test/java/dev/hilla/crud/FilterTest.java, packages/java/endpoint/src/test/java/dev/hilla/crud/NestedObject.java, packages/java/endpoint/src/test/java/dev/hilla/crud/SecondLevelNestedObject.java, packages/java/endpoint/src/test/java/dev/hilla/crud/TestObject.java
At the moment, properties of nested objects
with `@OneToOne` is automatically expanded
and shown as columns. The path for those
columns looks like `nestedObject.propertyName`
and this PR adds support for handling the
header filtering for those nested paths.
=> feat: add support for header filtering of nested properties

packages/ts/react-crud/src/autogrid-column-context.tsx, packages/ts/react-crud/src/autogrid.tsx, packages/ts/react-crud/src/header-sorter.tsx, packages/ts/react-crud/test/autogrid.spec.tsx, packages/ts/react-crud/test/grid-test-helpers.ts, packages/ts/react-crud/test/test-models-and-services.ts
Changes the auto-grid's internal sort state to support multi-sort. 
For now I did not enable multi-sort by default, as I found it quite bothersome that you first have to remove sort from one column (two clicks) if you just want to sort a different column (third click). Let's discuss this separately, maybe we can use the new multi-sort on shift click mode as a compromise.
Closes https://github.com/vaadin/hilla/issues/1509
=> feat: add multi-sort support to auto-grid

packages/java/parser-jvm-plugin-model/src/main/java/dev/hilla/parser/plugins/model/ModelPlugin.java, packages/java/parser-jvm-plugin-model/src/test/java/dev/hilla/parser/plugins/model/annotations/AnnotationsEndpoint.java, packages/java/parser-jvm-plugin-model/src/test/resources/dev/hilla/parser/plugins/model/annotations/openapi.json
This PR removes all annotation attributes as we don't need them right now. Trying to write them will easily lead to recursion.
Closes #1481
=> fix: remove infinite recursion when listing annotations in OpenAPI

packages/java/engine-runtime/src/main/java/dev/hilla/internal/TaskGenerateEndpointImpl.java, packages/java/engine-runtime/src/main/java/dev/hilla/internal/TaskGenerateOpenAPIImpl.java
Rather than counting on Flow to log exceptions, let's print them immediately in the logs and send a generic exception (without cause) to the caller.
Fixes #1530
=> Log exceptions immediately

.github/workflows/validation.yml
The gradle plugin should build in CI same as every other module. Otherwise bumping a snapshot version results in the plugin missing from the build, causing it to fail.
=> chore: fix building hilla gradle plugin

packages/ts/react-crud/src/autocrud.tsx, packages/ts/react-crud/src/autoform.tsx, packages/ts/react-crud/test/CrudController.ts, packages/ts/react-crud/test/autocrud.spec.tsx
Clears the form and removes the selection from grid when creating a new item. Also simplifies the grid selection logic a bit.
=> fix: reset form when creating new item

packages/java/tests/spring/react-grid-test/src/test/java/dev/hilla/test/reactgrid/AutoFormViewIT.java, packages/ts/react-crud/src/autoform.tsx, packages/ts/react-crud/test/FormController.ts, packages/ts/react-crud/test/autoform.spec.tsx
Shows a discard button in auto form if the form is dirty. Clicking the button resets the form.
Fixes #1433
=> feat: add discard button to auto form

packages/ts/react-crud/test/FormController.ts, packages/ts/react-crud/test/autoform.spec.tsx
Check Style errors didn't prevent the auto-merge from being triggered.
This address those remained errors from #1563
=> chore: fix check style errors remained from 1563

.github/workflows/skip-validation.yml, .github/workflows/validation.yml
Let us explicitly fail the validation summary job if any of the parallel test / check jobs failed. This aims primarily to make sure that GitHub auto-merge does not bypass the important validation steps.
=> chore: clarify validation summary

pom.xml
Pre-release dependency versions do not work for applications that depend on stable Hilla version, as the respective artifacts are only published on pre-release Maven repositories.
=> fix: depend on release versions of Flow and TestBench

packages/java/maven-plugin/src/main/java/dev/hilla/maven/BuildFrontendMojo.java
Changes the Hilla Maven plugin to not remove generated frontend files after the build. Those files can still be useful to developers after the build. For example, to run frontend tests in CI with vitest, you would like to keep the `vite.generated.ts` file.
=> chore: keep generated frontend files after build

.mocharc.json
Fixes the following issue during [test runs](https://github.com/vaadin/hilla/actions/runs/6640458023/job/18047435739?pr=1605):
```
@hilla/generator-typescript-cli: node:internal/process/esm_loader:40
@hilla/generator-typescript-cli:       internalBinding('errors').triggerUncaughtException(
@hilla/generator-typescript-cli:                                 ^
@hilla/generator-typescript-cli: Error: tsx must be loaded with --import instead of --loader
@hilla/generator-typescript-cli: The --loader flag was deprecated in Node v20.6.0
@hilla/generator-typescript-cli:     at X (file:///home/runner/work/hilla/hilla/node_modules/tsx/dist/esm/index.mjs:1:1920)
@hilla/generator-typescript-cli:     at Hooks.addCustomLoader (node:internal/modules/esm/hooks:178:24)
@hilla/generator-typescript-cli:     at …
```
=> chore: make mocha config work with Node 20.8

packages/ts/react-crud/src/autoform.tsx, packages/ts/react-crud/test/autoform.spec.tsx
Allows to define custom fields like this:
```tsx
customFields={{
lastName: ({ field }) => <TextArea {...field} label='Last name' />,
}}
```
When using custom fields, labels need to be specified by the developer. Anyway, we could add other items than `field` to the props.
Closes #1426.
=> feat(autoform): allow to define custom fields

packages/ts/react-crud/src/autocrud.tsx, packages/ts/react-crud/src/autoform.tsx, packages/ts/react-crud/test/FormController.ts, packages/ts/react-crud/test/autocrud.spec.tsx, packages/ts/react-crud/test/autoform.spec.tsx
Allows customizing the form and grid rendered by auto crud by passing respective props.
Fixes https://github.com/vaadin/hilla/issues/1614
=> feat: customize form and grid within auto crud

packages/ts/react-crud/src/autocrud.obj.css
Based on the UX feedback provided by Rolf, adds a box shadow to the form in auto-crud to have a clearer separation betwen the grid and the editor part.
=> feat: add box shadow to auto crud form

packages/ts/react-crud/src/autocrud.tsx, packages/ts/react-crud/src/autoform.tsx, packages/ts/react-crud/test/autocrud.spec.tsx, packages/ts/react-crud/test/autoform.spec.tsx
When not providing a custom class name to auto crud / form, it adds the class name `undefined`. This change sanitizes the class names to use an empty string as fallback if the class name is not defined.
=> fix: avoid adding 'undefined' as class name

packages/ts/react-crud/src/autocrud.tsx, packages/ts/react-crud/src/autoform-field.tsx, packages/ts/react-crud/src/autoform.tsx, packages/ts/react-crud/test/autocrud.spec.tsx, packages/ts/react-crud/test/autoform.spec.tsx
The way `AutoForm` is customized changes:
- `visibleFields` is used to list fields that are visible in the form (and their order)
- `formLayoutProps` is used to pass `responsiveSteps` and `ComponentStyleProps` properties to the default `FormLayout`
- `colspan` is added to `fieldOptions` and passed to the default `FormLayout`
- `customLayoutRenderder` is renamed to `layoutRenderer`
Closes #1678
=> feat(autoform): simplify basic form layout settings

packages/ts/react-crud/src/autoform-field.tsx, packages/ts/react-crud/test/autoform.spec.tsx
Also disables custom rendered fields if the auto form is disabled. This extends the `FieldDirectiveResult` type to include the disabled state. As a more opinionated change, I also moved the `label` into the `field` props, so that it is automatically applied as well. It's still possible to define a custom label via the renderer, and added a test for that. Both label + disabled should be fairly save to apply to any type of input field.
Fixes https://github.com/vaadin/hilla/issues/1685
=> fix: disable custom rendered fields in auto form

packages/ts/form/package.json, packages/ts/form/src/Binder.ts, packages/ts/form/src/BinderNode.ts, packages/ts/form/src/BinderRoot.ts, packages/ts/form/src/util.d.ts, packages/ts/form/test/Validation.test.ts
* fix(form): use correct call for interpolateMessageCallback
* fix(form): resolve typings failure
(cherry picked from commit ad5ee2b3ad3fcb87de72a55c503401a09093c6a2)
=> fix(form): use correct call for interpolateMessageCallback (#1694) (CP: 2.3)

packages/ts/react-crud/src/autoform-field.tsx, packages/ts/react-crud/src/autoform.tsx
Following feedback from the DX tests:
- Fixes the field renderer docs to remove the label prop that was removed
- Expands the form layout renderer docs and adds examples
=> refactor: clarify auto form renderer props

packages/ts/react-crud/package.json
Some versions are still lagging behind in branch 2.3. A new patch release is needed to avoid the `Tried to define vaadin-lumo-styles version 24.2.0 when version 24.2.1 is already in use. Something will probably break.` error.
=> chore(2.3) update CRUD dependencies

package-lock.json, packages/ts/frontend/src/Connect.ts, packages/ts/react-crud/package.json, packages/ts/react-crud/src/autoform.tsx, packages/ts/react-crud/test/autoform.spec.tsx
Fixes `frontend` error message logic.
Proposes a way to handle error types in Auto Form.
It works better if endpoints throw `EndpointException`s, as in that case it's able to get back the message of the original exception, but also works reasonably for other exceptions.
If this can be a good solution, I'll work on the tests.
Conflicts with #1715, we should make a choice.
=> fix(frontend+autoform): use proper error types

packages/ts/form/package.json, packages/ts/form/src/Binder.ts, packages/ts/form/src/BinderNode.ts, packages/ts/form/src/BinderRoot.ts, packages/ts/form/src/util.d.ts, packages/ts/form/test/Validation.test.ts, packages/ts/react-form/src/index.ts
* fix(form): use correct call for interpolateMessageCallback
* fix(form): resolve typings failure
(cherry picked from commit ad5ee2b3ad3fcb87de72a55c503401a09093c6a2)
=> fix(form): use correct call for interpolateMessageCallback (#1694) (CP: 2.2)

packages/ts/react-crud/src/autocrud.tsx, packages/ts/react-crud/src/autoform.tsx, packages/ts/react-crud/test/autocrud.spec.tsx
Based on the DX test feedback, most testers were not able to hide the delete button, as most tried to hide it through the `deleteButtonVisible` form prop, which was overridden by the auto crud's `noDelete` prop (which is not documented). This change removes the `noDelete` prop, so that hiding the button can only be done through `formProps`. This aligns it with how other form options are configured and also resolves the naming conflict. 
This also adds a note to the JS Doc that hiding the button does not prevent calling the service directly and advises for possible solutions.
=> fix: allow hiding delete button through form props

packages/java/tests/spring/react-grid-test/frontend/views/AutoFormView.tsx, packages/ts/react-crud/src/autocrud.tsx, packages/ts/react-crud/src/autoform.tsx, packages/ts/react-crud/test/autoform.spec.tsx
Renames:
- `afterSubmit` -> `onSubmitSuccess`
- `afterDelete` -> `onDeleteSuccess`
This ensures the event handler are prefixed with `on`, which is how event handlers are commonly named in React, and also aligns the event handler better with their error counterparts (`onSubmitSuccess` / `onSubmitError`, `onDeleteSuccess` / `onDeleteError`).
Fixes #1733
=> refactor!: improve auto form event handler naming

packages/ts/react-crud/test/autoform.spec.tsx
Tests were accidentally disabled in #1751 , this should re-enable them.
=> test: re-enable react-crud tests

packages/java/tests/csrf-context/pom.xml, packages/java/tests/csrf/pom.xml, packages/java/tests/pom.xml
Some tests are failing due a new Jetty version that doesn't seem to work with our test setup.
Tests are failing only when executed from the project root directory.
This PR simply restores the old Jetty version for those tests.
=> chore: restore previous Jetty version

packages/ts/react-crud/src/autocrud.tsx, packages/ts/react-crud/test/autocrud.spec.tsx
The `formProps` in `AutoCrud` are currently typed so that the type for the model becomes something like `AbstractModel<Person>`, while it should be `PersonModel`. As a consequence, when using a custom form layout renderer the `form.model` is a `AbstractModel<Person>`, which prevents you from accessing the model fields.
This changes the generic type param for `AutoCrud` to be based on the model, rather than the item, which allows reusing it for declaring the form props. This is technically a breaking change.
=> fix!: use proper model type in auto crud

packages/java/engine-core/src/main/java/dev/hilla/engine/commandrunner/CommandRunner.java, packages/java/engine-core/src/test/java/dev/hilla/engine/commandrunner/CommandRunnerTest.java
When `CommandRunner` cannot find a valid executable for a task, it emits an error message which does not indicate the commands that have been searched.
While detailed information is available when using `debug` log level, it is wise to add the executable names to the default message.
=> fix: add executable names to not found message

packages/ts/react-crud/src/autoform-field.tsx, packages/ts/react-crud/src/locale.ts, packages/ts/react-crud/test/autoform.spec.tsx
Make `AutoForm`'s `AutoDateTimeField` use the same localized date format that is used in other fields and renderers.
=> fix: use localized date format in date time field

packages/java/engine-core/src/main/java/dev/hilla/engine/commandrunner/GradleRunner.java, packages/java/engine-core/src/main/java/dev/hilla/engine/commandrunner/MavenRunner.java, packages/java/engine-core/src/test/java/dev/hilla/engine/commandrunner/GradleRunnerTest.java, packages/java/engine-core/src/test/java/dev/hilla/engine/commandrunner/MavenRunnerTest.java
Allows to specify a custom executable path for maven and gradle runners that takes priority over default hard-coded executables.
Fixes #1749
=> feat: allow custom runner executable path

packages/ts/react-crud/src/autocrud.tsx, packages/ts/react-crud/src/autogrid.tsx, packages/ts/react-crud/test/autogrid.spec.tsx
Exposes the underlying `vaadin-grid` DOM element on the `AutoGridRef`. That allows using other imperative API of the grid, for example `getEventContext` to get details about an item in a context menu.
=> feat: expose grid element from auto grid ref

packages/ts/react-crud/src/autoform-field.tsx, packages/ts/react-crud/src/autoform.tsx, packages/ts/react-crud/test/autoform.spec.tsx
Adds more common field properties to `fieldOptions`:
- `id`
- `className`
- `style`
- `readonly`
- `disabled`
- `placeholder`
- `helperText`
`placeholder` and `helperText` are not supported by component types, for example checkbox doesn't have either, and a select with a preselected value can never show a placeholder. Still think they are useful to have by default.
As for more specific properties that only apply to some components I think we are at a dead-end with this approach - there isn't any way how we could properly type the respective field options object so that it accepts props for the respective component. 
One idea I had was to allow passing a prerendered JSX element to `renderer` which we would then enhance with the other options and the form binding. That would be easier than …
=> feat: add more common props to field options

packages/java/hilla-dev-mode/src/main/resources/META-INF/resources/frontend/dev-tools-database.ts
field decorators are currently problematic when projects can use useDefineForClassFields true or false
=> fix: Avoid using decorators

packages/ts/react-crud/src/autogrid-renderers.tsx, packages/ts/react-crud/src/autogrid.tsx, packages/ts/react-crud/src/data-provider.ts, packages/ts/react-crud/test/autogrid.spec.tsx, packages/ts/react-crud/test/dataprovider.spec.ts
Separates the data provider implementation from `AutoGrid` specific logic:
- Moves the DP implementation into a separate module
- Refactored the data providers to be class based, with specific implementations for infinite and fixed-size data providers.
- Moves the `recalculateColumnWidths` workaround back to the `AutoGrid`
- Removes the item count holder and footer ref, and instead provides a callback that returns the total and filtered item counts
- Adds test coverage for the DP implementation itself
Also refactors the footer item count logic a bit:
- The footer ref has been removed. Instead the `AutoGrid` now has a state for the item counts, which is passed down into the footer column context to trigger a re-render when the item counts change.
- Changed the signature of the custom …
=> refactor: separate data provider logic from auto grid

packages/java/plugin-base/src/main/java/dev/hilla/plugin/base/HillaAppInitUtility.java
=> fix: make init-app goal generate sources coherent with the project Hilla version

packages/ts/form/src/Validation.ts, packages/ts/form/src/Validators.ts, packages/ts/form/test/Validators.test.ts
This adds the possibility of defining a name
for all the validators implementing this
interface, which helps to preserve validator's
name in production mode, which is needed when
interpolating messages for client-side validators
(including those added to the binder based on the
existence of JSR380 jakarta validation annotations 
on the endpoints transfer types).
Fixes #1840
=> fix: add name property to Validator interface

packages/ts/react-form/src/index.ts, packages/ts/react-form/test/useForm.spec.tsx
Fixes https://github.com/vaadin/hilla/issues/1164
=> fix: expose submitting state

packages/java/plugin-base/src/main/java/dev/hilla/plugin/base/HillaAppInitUtility.java, packages/java/plugin-base/src/test/java/dev/hilla/plugin/base/HillaAppInitUtilityTest.java
Currently, React applications that are initialized with HillaAppInitUtility don't have a package-info.java file, which causes typescript errors at startup because of missing nullable annotation.
This change adds handling of package-info.java file during the scaffolding process.
Fixes #1935
=> fix: produce package-info.java file in scaffolded application

packages/ts/react-crud/src/autocrud-dialog.tsx, packages/ts/react-crud/src/autocrud.obj.css, packages/ts/react-crud/src/autocrud.tsx, packages/ts/react-crud/test/autocrud.spec.tsx
Adds a customizable header above the form in `AutoCrud`. By default it shows `New item` and `Create item` depending on whether a new item is created or an existing one edited. It's also possible to customize the header by providing a function that renders a custom JSX element based on the edited item and the disabled state of the form. The header is part of the `AutoCrud` for now instead of the `AutoForm`. Otherwise it would have been a challenge to move it into the header of the dialog that shows up on smaller screens.
Disabled:
Editing:
Creating:
=> feat: add customizable form header to auto crud

packages/java/maven-plugin/src/main/java/com/vaadin/hilla/maven/BuildFrontendMojo.java, packages/java/maven-plugin/src/main/java/com/vaadin/hilla/maven/CleanFrontendMojo.java, packages/java/maven-plugin/src/main/java/com/vaadin/hilla/maven/ConvertPolymerMojo.java, packages/java/maven-plugin/src/main/java/com/vaadin/hilla/maven/FrontendDanceMojo.java
Since platform repackages hilla-maven-plugin instead of flow-maven-plugin we should not disable flow specific goals
There should be code in flow or hilla skiping certain goals based on configured or computed flags
=> chore: reenable flow specific goals in hilla-maven-plugin

packages/java/tests/csrf-context/pom.xml, packages/java/tests/pom.xml, packages/java/tests/spring/react-grid-test/pom.xml
Removes `reactRouterEnabled` config parameter everywhere from test modules as now Flow has auto-detection and should manage to do it without this parameter.
=> chore: Remove react router config parameter from tests

packages/java/gradle-plugin/build.gradle
After renaming the `dev.hilla` to `com.vaadin.hilla`
the config for sources-jar inclusion was still
pointing to `dev/**`
=> fix gradle plugin source jar

packages/java/tests/pom.xml
This is needed in order not to make hilla tests depend on platform vaadin-dev
=> chore: add hilla-dev dependency to tests so as they can be run in devmode

packages/java/maven-plugin/pom.xml
When generating an endpoint that extends `ListRepositoryService`, for some reason that class is now loaded by a different class loader. That didn't happen in Hilla 2.5. That class loader uses the classpath of the plugin, not the one of the project.
This PR provides the necessary dependency at plugin level.
Fixes https://github.com/vaadin/hilla/issues/2117
=> fix: provide necessary dependency in plugin classpath

packages/ts/react-form/src/index.ts, packages/ts/react-form/test/useForm.spec.tsx
Fixes #2134
- Bugfix
Note: I'm not very happy with my approach to test this (like, I'd prefer to spy on validator). Suggestions are welcome.
Also, ideally we wouldn't need to use `fireEvent` manually, as native `<input type="number">` fires it on <kbd>Enter</kbd>.
But for some reason `user.type(projectInput, '123[Enter]')` didn't work this way, probably RTL doesn't handle this case.
=> fix: mark as visited on change in addition to blur

packages/java/maven-plugin/pom.xml
This will reintroduce https://github.com/vaadin/hilla/issues/2117, but https://github.com/vaadin/platform/pull/5121 should fix it.
=> fix: remove spring-data-jpa from Maven Plugin deps

.github/workflows/validation.yml
Since Gradle tests are executed on both ubuntu and window machines, uploading the artifact with the same name results in conflict, and the slower build (normally windows) fails to upload because of that.
=> chore: fix conflict in artifact name while uploading

packages/java/tests/spring/react-signals/pom.xml
This enables Signals ITs to use the same config as the rest of the integration tests, 
especially to execute the IT app in production mode.
=> test: fix hilla-maven-plugin groupId in signals IT

packages/java/maven-plugin/src/main/java/com/vaadin/hilla/maven/EngineConfigureMojo.java
Use `FrontendUtils.DEFAULT_PROJECT_FRONTEND_GENERATED_DIR` instead of the literal value of frontend/generated.
Fixes #2167
=> fix: use the new default value for frontend/generated

packages/java/endpoint/src/main/java/com/vaadin/hilla/startup/RouteUnifyingServiceInitListener.java
If the resource is valid, there's no need to check that the corresponding file is there, which is not true in production anyway, given that it's in a JAR.
Fixes #2203
=> fix(fsrouter): remove check for file existence

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/startup/RouteUnifyingServiceInitListener.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/startup/RouteUnifyingServiceInitListenerTest.java
Also, this changes the behavior of client route registration so that when the views.json is not found, it only logs its absence, and it gracefully skips client route registration. This is necessary as an application might have React enabled, but it is not necessarily using the FS Router.
=> fix: register RouteUnifyingIndexHtmlRequestListener only when React is enabled

packages/java/endpoint/pom.xml, packages/java/hilla-bom/pom.xml, pom.xml
This also set the `enforcer.skip` for the hilla-bom module to skip the unnecessary execution of enforcer plugin in that module.
=> chore: upgrade atmosphere runtime to 3.0.5.slf4jvaadin1

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUtil.java, packages/ts/file-router/src/types.d.ts, packages/ts/react-auth/src/useAuth.tsx
As `jakarta.annotation.security.RolesAllowed` does not allow to specify an empty list of roles (compilation error), let's adopt the same behavior in Hilla.
This is a breaking change in the unlikely case that someone has used an empty list of roles, as now his TypeScript code won't compile anymore.
Fixes #2246.
=> fix!: require at least one role in `rolesAllowed`

pom.xml
This fix the dependency convergence error in builds.
=> chore: upgrade javaparser-core version

packages/java/endpoint/pom.xml, packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListener.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUtil.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/startup/RouteUnifyingServiceInitListener.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/startup/RouteUnifyingServiceInitListenerTest.java, packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-admin.json, packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-anonymous.json, packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-user.json, packages/java/endpoint/src/test/resources/META-INF/VAADIN/only-client-views.json
This enables filtering of Hilla views based on the security configurations exported from views, and uses the same access control API that could be optionally used Spring Security configuration for http level security.
It is important to note that filtering Hilla views in the menu is a usability feature not a security one.
=> feat: utilize access control when populating client-side routes in menu

packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts, packages/ts/file-router/test/runtime/RouterBuilder.spec.tsx
=> fix(file-router): make empty path index resolving correctly

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUtil.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUtilTest.java
`RouteUtil` becomes an optional bean that, when Hilla is used, is automatically taken into account in `VaadinWebSecurity`.
Needs https://github.com/vaadin/flow/pull/19257 to compile.
Closes #2357.
=> feat: make `RouteUtil` implement Flow interface

packages/ts/file-router/src/vite-plugin/collectRoutesFromFS.ts, packages/ts/file-router/src/vite-plugin/generateRuntimeFiles.ts, packages/ts/file-router/test/vite-plugin/generateRuntimeFiles.spec.ts
Should eliminate errors like
```
Error: ENOENT: no such file or directory, opendir '/opt/agent/work/83e2cf1ab9bef258/frontend/views/'
```
for projects that has no `views` folder.
=> fix: Do not collect if views does not exist

packages/java/hilla-dev/pom.xml
This is an alternative for https://github.com/vaadin/platform/pull/5264 that prevents `hilla-dev` to include Hilla artifacts (endpoint artifact) into projects that don't use Spring and Hilla.
Fixes https://github.com/vaadin/platform/issues/5260
=> chore: Make hilla endpoint optional for plugin

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListener.java, packages/ts/file-router/src/runtime/createMenuItems.ts, packages/ts/file-router/src/shared/internal.d.ts, packages/ts/file-router/test/runtime/createMenuItems.spec.ts
As `Vaadin.server.views` holds both server-side
and client-side views, having the `server` in the
naming of that object can confuse users. This 
changes the object to `Vaadin.views`.
Fixes #2375
=> refactor!: rename Vaadin.server.views object to Vaadin.views

packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/BackbonePlugin.java, packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/JsonValuePlugin.java, packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/hilla/parser/plugins/backbone/jsonvalue/Endpoint.java, packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/hilla/parser/plugins/backbone/jsonvalue/JsonValueEndpoint.java, packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/hilla/parser/plugins/backbone/jsonvalue/JsonValueTest.java, packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/hilla/parser/plugins/backbone/jsonvaluenojsoncreator/Endpoint.java, packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/hilla/parser/plugins/backbone/jsonvaluenojsoncreator/JsonValueNoJsonCreatorEndpoint.java, packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/hilla/parser/plugins/backbone/jsonvaluenojsoncreator/JsonValueNoJsonCreatorTest.java, packages/java/parser-jvm-plugin-backbone/src/test/resources/com/vaadin/hilla/parser/plugins/backbone/jsonvalue/openapi.json
Adds support for `@JsonCreator` and `@JsonValue` annotations to allow to customize how a type is transferred.
The main purpose is to provide support for domain primitives, like:
```java
public record Email(@JsonValue String value) {
@JsonCreator public Email {}
}
```
Fixes #2055
=> feat(generator): support `@JsonCreator` and `@JsonValue` annotations

scripts/prepare/index.ts
Versions collected during the build are restructured in a way that there is no immediate `"react"` child for versions (root object) in the [scripts/prepare/index.ts](https://github.com/vaadin/hilla/blob/main/scripts/prepare/index.ts#L66), but under "core" and "vaadin" (core and commercial), which leads to a runtime error during the builds. 
This fixes the issue by reading the version of `react-components` from the `versions.core` instead.
=> chore: fix ts build script

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/records/ClientViewMenuConfig.java
Changing ClientViewMenuConfig order field type from Long to Double to match with Flow's RouteData and Menu annotation.
Related-to: vaadin/flow/issues/19332
=> chore: change ClientViewMenuConfig order type

packages/java/endpoint/src/main/resources/META-INF/VAADIN/package.properties
Flow uses package.properties file to optimize class scanning to only include relevant package from the hilla-endpoint jar.
Related-to: vaadin/flow/issues/19117
=> chore: add package.properties

packages/ts/file-router/src/vite-plugin.ts
Fixes #2410.
It looks like the lookbehind feature in `RegExp` is extremely slow. I replaced it with the regular `RegExp`, and according to my measurements, it is almost instant.
=> fix(file-router): improve the speed of the HMR injection

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java
=> fix: ignore absence of file-routes.json at startup in dev mode

packages/java/endpoint/src/main/java/com/vaadin/hilla/ExplicitNullableTypeCheckerHelper.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/ExplicitNullableTypeCheckerTest.java, packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/TypeSignaturePlugin.java, packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/hilla/parser/plugins/backbone/iterable/IterableEndpoint.java, packages/java/parser-jvm-plugin-backbone/src/test/resources/com/vaadin/hilla/parser/plugins/backbone/iterable/openapi.json, packages/java/parser-jvm-utils/pom.xml, packages/java/parser-jvm-utils/src/main/java/com/vaadin/hilla/parser/utils/Generics.java, packages/java/parser-jvm-utils/src/main/java/module-info.java
This PR introduces a dependency from `gentyref`. This library is already used in Flow Server and thus nothing new is added to user applications.
Fixes #2391
=> fix: support classes that extend or implement an Iterable

pom.xml
Depends on https://github.com/vaadin/testbench/pull/1795
=> chore: use testbench snapshot in main

scripts/prepare.sh
=> chore: use branch name instead of release tag (2.5)

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListener.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java, packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-admin.json, packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-anonymous.json, packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-user.json
Fixes server menu item url for routes with route parameter with a wildcard like (route/:param*).
RelatedTo: vaadin/flow/issues/19392
=> fix: support wildcard route parameter in menu

packages/java/endpoint/src/main/java/com/vaadin/hilla/OpenAPIUtil.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/OpenAPIUtilTest.java, packages/java/endpoint/src/test/resources/com/vaadin/hilla/openapi-noendpoints.json
=> fix: Do not skip endpoint registration if there are no custom types

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java, packages/java/endpoint/src/test/resources/META-INF/VAADIN/file-routes.json, packages/ts/file-router/src/shared/internal.d.ts, packages/ts/file-router/src/vite-plugin/createViewConfigJson.ts, packages/ts/file-router/test/utils.tsx, packages/ts/file-router/test/vite-plugin/createViewConfigJson.spec.ts
=> refactor(file-router): make route with non-null children detected as a layout

packages/ts/form/src/BinderNode.ts, packages/ts/form/test/Binder.test.ts, packages/ts/form/test/TestModels.ts, packages/ts/form/test/Validation.test.ts
=> fix(form): initialize value / defaultValue keys when rendering optional fields

packages/java/hilla-bom/pom.xml, packages/java/hilla/pom.xml
this seems has been missing from the beginning of our project. without it, there is missing deploy settings to maven central
=> chore: add parent project for hilla-bom (24.4)

packages/java/endpoint/src/main/java/com/vaadin/hilla/startup/RouteUnifyingServiceInitListener.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/startup/RouteUnifyingServiceInitListenerTest.java
When `isReactEnabled=false` the stats reporting method `HillaStats.reportGenericHasFeatures` wasn't invoked making Lit stats not reported at all.
Related-to https://github.com/vaadin/platform/issues/6488
=> fix: Report usage stats when isReactEnabled=false

packages/java/hilla-bom/pom.xml
using hilla-project brings the `<dependencyManangement>` from parent, which is not the one want
=> chore: use vaadin-parent 2.2.1 as parent for hilla-bom

pom.xml
```
[ERROR] +-com.vaadin:vaadin:jar:24.4-SNAPSHOT
[ERROR]   +-com.vaadin:vaadin-internal:jar:24.4-SNAPSHOT:compile
[ERROR]     +-com.vaadin:vaadin-core-internal:jar:24.4-SNAPSHOT:compile
[ERROR]       +-com.vaadin:flow-server:jar:24.4-SNAPSHOT:compile
[ERROR]         +-commons-io:commons-io:jar:2.16.1:compile
[ERROR] and
[ERROR] +-com.vaadin:vaadin:jar:24.4-SNAPSHOT
[ERROR]   +-com.vaadin:vaadin-spring-boot-starter:jar:24.4-SNAPSHOT:compile
[ERROR]     +-com.vaadin:hilla:jar:24.4.1:compile
[ERROR]       +-com.vaadin:hilla-endpoint:jar:24.4.1:compile
[ERROR]         +-commons-io:commons-io:jar:2.13.0:compile
```
=> chore: upgrade commons-io to 2.16.1

packages/java/hilla-bom/pom.xml
repo declaration is needed as the parent project is now `vaadin-parent` which doesn't include repo settings.
without this declaration, flattened pom will not have vaadin-prerelease repos, so the release build will fail
=> chore:add repo declaration

packages/ts/file-router/src/vite-plugin/createRoutesFromMeta.ts, packages/ts/file-router/test/utils.tsx, packages/ts/file-router/test/vite-plugin/createRoutesFromMeta.spec.ts, packages/ts/file-router/test/vite-plugin/createViewConfigJson.spec.ts
=> fix(file-router): preserve empty children for layout routes

.mocharc.cjs, package-lock.json, package.json, scripts/hooks.js
Update `tsx` to the version with privatenumber/tsx#506 fixed
=> chore: fix `tsx` not stopping on breakpoints

packages/java/maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
Adds `lifecycle-mapping-metadata.xml` like in Flow plugin, but using `generate` as incremental goal.
Should fix both https://github.com/vaadin/platform/issues/6562 and https://github.com/vaadin/platform/issues/6590.
=> feat(maven-plugin) add m2e metadata

packages/java/endpoint/pom.xml, pom.xml
This is to fix the dependency convergence error for atmosphere runtime version conflict between Flow and Hilla.
=> chore: upgrade flow to fix atmosphere runtime convergence

package-lock.json, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/NumberSignal.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/core/SignalsRegistry.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/core/StateEvent.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/handler/SignalsHandler.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/signals/NumberSignalTest.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/signals/core/SignalsRegistryTest.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/signals/core/StateEventTest.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/signals/handler/SignalsHandlerTest.java, packages/java/tests/spring/react-signals/package-lock.json, packages/java/tests/spring/react-signals/src/test/java/com/vaadin/hilla/test/NumberSignalIT.java, packages/ts/react-signals/package.json, packages/ts/react-signals/src/EventChannel.ts, packages/ts/react-signals/src/Signals.ts
We do not need security-grade random ids neither
for the events being exchanged between client and
server, nor for the client-side signal instances.
Since `crypto.randomUUID()` was creating problems
for executing tests on hub (with no https connection), 
it is replaced with the nanoid npm package.
This also refactor the server-side APIs to replace UUID
type for client-side signal ids to be string, and keeps 
using UUID only for the server-side signal ids.
=> refactor: use nanoid instead of crypto.randomUUID

package-lock.json, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/core/registry/SecureSignalsRegistry.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/handler/SignalsHandler.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/signals/core/registry/SecureSignalsRegistryTest.java, packages/java/tests/spring/react-signals/package-lock.json, packages/java/tests/spring/react-signals/package.json, packages/ts/react-signals/src/FullStackSignal.ts, packages/ts/react-signals/test/FullStackSignal.spec.tsx
=> feat: add automatic subscribe/unsubscribe to signals

.github/workflows/validation.yml
It seems that the it takes more than 5 minutes for the validation build step "Build Java and TypeScript for other tasks" to be done. This increases the timeout.
=> chore: increase build java and typescript validation step timeout

packages/ts/generator-cli/package.json, packages/ts/generator-plugin-backbone/package.json, packages/ts/generator-plugin-barrel/package.json, packages/ts/generator-plugin-client/package.json, packages/ts/generator-plugin-model/package.json, packages/ts/generator-plugin-push/package.json, packages/ts/generator-plugin-signals/package.json, packages/ts/generator-plugin-subtypes/package.json
As pointed out in https://github.com/npm/cli/issues/7719, npm struggles with resolving peer dependencies when running `npm install` and applying new peer dependency requirements that do not align with previously installed versions. In many cases it produces an unexpected error for the user instead of updating installed peer dependency packages.
As a (temporary?) workaround, let us avoid using strict peer dependency requirements for our packages.
This changes the `package.json` to use regular dependency version spec even though the expectation is that the install is “flat”, i. e., the packages are is installed on the top-level of `node_modules/` in the user application.
=> fix(TypeScript): npm peer dependency install conflicts in user applications

packages/ts/generator-plugin-model/src/EntityModelProcessor.ts
The entity generator emits a `debug` log to warn about entities without properties. The model generator emits a real `warn`-level message.
This PR removes this second message.
Fixes #2506.
=> fix: remove warning on entities with no properties

packages/ts/react-crud/src/autoform.tsx, packages/ts/react-crud/test/autoform.spec.tsx
=> fix: do not submit autoform on key-down if pressed in textarea

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListener.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ServerAndClientViewsProvider.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/startup/RouteUnifyingServiceInitListener.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java
=> refactor: Extract code that creates window.Vaadin.views json

packages/java/endpoint/src/main/java/com/vaadin/hilla/startup/RouteUnifyingServiceInitListener.java, packages/ts/file-router/src/runtime/createMenuItems.ts, packages/ts/file-router/src/vite-plugin.ts, packages/ts/file-router/src/vite-plugin/generateRuntimeFiles.ts, packages/ts/file-router/test/vite-plugin/vite-plugin.spec.ts
HMR now works as following:
When a file inside the `views` folder changes, the vite plugin for the file router picks that up.
After writing file-routes.ts and file-routes.json with the new data, it fires a `fs-route-update` event through the Vite event bus. It is important to write `file-routes.ts` also when its contents does not change but some meta info in a view has changed (i.e. when the json file changes). This will propagate the new meta data also to the router configuration.
The custom HMR code in `createMenuItems.ts` reacts to this events and initiates a re-fetch of `window.Vaadin.views` from the server. Once the new data is available, the signal the menu is based upon is updated and the menu re-rendered.
Vite reacts on `file-routes.ts` being changed and propagates HMR events to …
=> feat: Do not force full reload when changing routes

packages/ts/lit-form/src/Field.ts, packages/ts/lit-form/test/Field.test.ts, packages/ts/react-crud/test/autocrud.spec.tsx
Introduce a checkbox group field strategy to set an empty array instead of undefined as the field doesn't support undefined value change.
Fixes #2547
=> fix: checkbox group undefined field strategy

packages/ts/frontend/src/Connect.ts, packages/ts/frontend/src/FluxConnection.ts, packages/ts/frontend/test/FluxConnection.test.ts, packages/ts/react-signals/test/FullStackSignal.spec.tsx, packages/ts/react-signals/test/utils.ts
Remove onDisconnect callback as for https://github.com/vaadin/hilla/pull/2737 and later introduce the onConnectionStateChange callback.
Fixes: #398 and #2769
=> fix: remove onDisconnect callback from flux subscription

packages/ts/file-router/src/vite-plugin/createViewConfigJson.ts
When Hilla view has no config, make sure to create a minimal config for it, containing the `flowLayout` value.
Fixes https://github.com/vaadin/flow/issues/20110
=> fix: if config doesn't exist, add minimal one with flowLayout

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListener.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUtil.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ServerAndClientViewsProvider.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/startup/RouteUnifyingServiceInitListener.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java, packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-admin.json, packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-anonymous.json, packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-user.json, packages/java/endpoint/src/test/resources/META-INF/VAADIN/only-client-views.json, packages/java/endpoint/src/test/resources/META-INF/VAADIN/server-and-client-views.json
RelatedTo: vaadin/flow/issues/20063
=> chore: update imports to MenuRegistry

packages/ts/lit-form/src/Field.ts, packages/ts/lit-form/test/Field.test.ts, packages/ts/react-crud/src/model-info.ts, packages/ts/react-crud/test/model-info.spec.ts
- Always convert it to YYYY-MM-ddTHH:mm:ss.SSS as other formats are not allowed for time being (https://github.com/vaadin/web-components/pull/3953#discussion_r902399701)
- Add support for other datetime types, but formatting must be done by server
Fixes: https://github.com/vaadin/hilla/issues/2770
and adds support for https://github.com/vaadin/hilla/issues/2390-
For time zone types, @JsonConverter or @JsonDeserializer needs to be used, as DateTimePicker does not support time zones, so that time zone is adjusted on the server side.
=> fix: localdatetime fills in AutoCrud and allow other java time classes to be used automatically

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ServerAndClientViewsProvider.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java, packages/java/endpoint/src/test/resources/META-INF/VAADIN/server-and-client-views-layout-and-index-route.json, packages/java/endpoint/src/test/resources/com/vaadin/hilla/route/clientRoutesWithLayoutAndIndexView.json
`MenuRegistry::collectClientViews` erases/overrides the layout entry by the view entry, if they have the same mapping, e.g. when you add `@layout.tsx` and `@index.tsx` in the same folder.
Thus, the `ServerAndClientViewsProvider::hasMainMenu` method may not get all the layouts in the input collection.
That leads to hasMainMenu=false and to skipping menu entries for Flow routes.
This patch uses https://github.com/vaadin/flow/pull/20245 new method to detect top-level main layout that fulfils the same criteria: empty route, non-null children, no other root elements.
Related-to https://github.com/vaadin/hilla/issues/2825
=> fix: Check main layout presence separately

packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ServerAndClientViewsProvider.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java, packages/java/endpoint/src/test/resources/META-INF/VAADIN/server-and-client-views-layout-and-index-route.json, packages/java/endpoint/src/test/resources/com/vaadin/hilla/route/clientRoutesWithLayoutAndIndexView.json
MenuRegistry::collectClientViews erases/overrides the layout entry by the view entry, if they have the same mapping, e.g. when you add @layout.tsx and @index.tsx in the same folder.
Thus, the ServerAndClientViewsProvider::hasMainMenu method may not get all the layouts in the input collection.
That leads to hasMainMenu=false and to skipping menu entries for Flow routes.
This patch uses https://github.com/vaadin/flow/pull/20245 new method to detect top-level main layout that fulfils the same criteria: empty route, non-null children, no other root elements.
Related-to https://github.com/vaadin/hilla/issues/2825
=> fix: Check main layout presence separately (#2831)(CP: main)

packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/TypeSignaturePlugin.java, packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/nodes/TypeSignatureNode.java, packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/hilla/parser/plugins/backbone/generics/GenericsBareEntityEndpoint.java, packages/java/parser-jvm-plugin-backbone/src/test/resources/com/vaadin/hilla/parser/plugins/backbone/generics/openapi.json
Adds position information to `TypeSignatureNode` so that identical type arguments are retained thanks to their different position.
Fixes #2847
=> fix(parser): add position information to type signature node

packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java
Mock object should call MenuAccessControl.canAccessView default method, that also requires VaadinRequest thread local to be set.
=> test: fix MenuAccessControl mocking

packages/ts/lit-form/package.json, packages/ts/lit-form/src/Field.ts
Existing for VaadinDateTimePickerStrategy failed when running in non-UTC timezone environment. This change addresses the bug and makes the form library tests always use a non-UTC timezone.
=> fix(form): support non-UTC timezone date time in VaadinDateTimePicker

packages/ts/react-crud/src/locale.ts
Assigning year, month, and day, in this order, is problematic when the chosen month has less days than the current day of month.
So, for example, on Oct. 31st 2024, choosing Sept. 15th 2024 leads to 2024 -> Sept. 31 -> Oct. 1 -> Oct. 15.
Passing the 3 parameters at once avoids this problem.
Fixes #2887
=> fix(crud): use 3-params overload for dates instead of separate assignments

scripts/prepare/generate.ts
Adds a fake `process` to script context to allow building Hilla with recent Platform script requirements.
=> fix(build): add `process` to script context

packages/java/maven-plugin/src/test/java/com/vaadin/hilla/maven/AbstractMojoTest.java, packages/java/maven-plugin/src/test/java/com/vaadin/hilla/maven/EngineGenerateMojoTest.java, packages/java/maven-plugin/src/test/resources/com/vaadin/hilla/maven/hilla-engine-configuration.json
Refactoring required by changes in vaadin/flow#20465.
=> test: refactor mock setup in maven plugin tests

packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/NumberSignal.java
This improves the logic in the javadoc example.
=> chore: improve javadoc example

karma.config.cjs, package-lock.json, package.json, packages/ts/react-auth/package.json, packages/ts/react-auth/tsconfig.json, scripts/types.d.ts, scripts/vite/plugins.ts, scripts/vite/test-utils.ts, vite.config.ts, wtr.config.ts
Fixes test failures in #2901 by replacing Karma Test Runner (deprecated) with Web Test Runner.
Web Test Runner is applied only to the `react-auth` package. The plan is to incrementally transfer other browser-based packages over time.
=> chore: add web-test-runner for react-auth

package-lock.json, packages/ts/file-router/package.json, packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts, packages/ts/file-router/src/runtime/createRoute.ts, packages/ts/file-router/src/shared/transformTree.ts, packages/ts/file-router/src/vite-plugin/applyLayouts.ts, packages/ts/file-router/src/vite-plugin/createRoutesFromMeta.ts, packages/ts/file-router/src/vite-plugin/createViewConfigJson.ts, packages/ts/file-router/src/vite-plugin/generateRuntimeFiles.ts, packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx, packages/ts/file-router/test/vite-plugin/applyLayouts.spec.ts, packages/ts/file-router/test/vite-plugin/createRoutesFromMeta.spec.ts
In case `layouts.json` contains a module extension (`flowLayout: true`) for a specific route that is not represented by either regular file or a `@layout.tsx`, we should be able to apply that extension on the route. This PR allows the route `module` to be null though still have the extension.
=> fix(file-router): allow extension to apply on a route wrapper

packages/java/endpoint/src/main/java/com/vaadin/hilla/EndpointControllerConfiguration.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/config/SignalsConfiguration.java
Having Hilla related beans prefixed with hilla
prevents clash with other framework or user
beans.
Fixes #2955
=> fix!: rename Hilla's endpointObjectMapper to prevent bean name clashes

packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/ListSignal.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/NumberSignal.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/Signal.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/ValueSignal.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/config/SignalsConfiguration.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/core/event/InvalidEventTypeException.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/core/event/ListStateEvent.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/core/event/MissingFieldException.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/core/event/StateEvent.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/core/registry/SecureSignalsRegistry.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/core/registry/SignalsRegistry.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/handler/SignalsHandler.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/operation/IncrementOperation.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/operation/ListInsertOperation.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/operation/ListRemoveOperation.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/operation/OperationValidator.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/operation/ReplaceValueOperation.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/operation/SetValueOperation.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/operation/SignalOperation.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/operation/ValidationResult.java, packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/operation/ValueOperation.java, packages/ts/react-crud/src/util.tsx
This adds missing license headers to the files in the signals package.
=> chore: add missing license headers to signals package

.github/workflows/validation.yml
Without this step, it's not the current plugin version that is tested, but the older one.
=> chore(build): add `publishToMavenLocal` to Gradle validation

packages/ts/file-router/src/vite-plugin.ts
=> fix: Make file route HMR work on Windows

packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts, packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx
* refactor(file-router): attempt to consider all routes with the same path
* refactor(file-router): allow elements with same path in the route list
* style(file-router): cleanup
* chore: update package-lock.json
* test(file-router): fix index fallback assertion
* chore: revert package-lock.json
* chore(file-router): remove extra dependency
* chore(generator-utils): remove unnecessary export
* chore: revert package-lock.json
* chore(file-router): do not bring old tests back
=> fix(file-router): allow routes with the same path (#2971) (CP: 24.6)

packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts, packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx
The combination use cases with file routes, server layout, and server fallback were broken in #2971. This fixes the combination issue and adds a test.
=> fix(file-router): enable file routes + layout + fallback combination

packages/ts/react-crud/src/data-provider.ts, packages/ts/react-crud/test/autogrid.spec.tsx, packages/ts/react-crud/test/dataprovider.spec.tsx
Without this, I see an exception for all sort requests
```
Caused by: java.lang.UnsupportedOperationException: Applying Null Precedence using Criteria Queries is not yet supported.
at org.springframework.data.jpa.repository.query.QueryUtils.toJpaOrder(QueryUtils.java:757) ~[spring-data-jpa-3.4.0.jar:3.4.0]
at org.springframework.data.jpa.repository.query.QueryUtils.toOrders(QueryUtils.java:706) ~[spring-data-jpa-3.4.0.jar:3.4.0]
at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getQuery(SimpleJpaRepository.java:756) ~[spring-data-jpa-3.4.0.jar:3.4.0]
at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getQuery(SimpleJpaRepository.java:714) ~[spring-data-jpa-3.4.0.jar:3.4.0]
at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findAl …
```
=> fix: set NullHandling to native when sorting

karma.config.cjs
This reduces randomness when tests are run on different machines and resolves the current issue of a date field going into "mobile mode" and not having an input field on GitHub Actions
=> test: Define window size

packages/java/parser-jvm-core/src/main/java/com/vaadin/hilla/parser/core/ScanResult.java, packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/EndpointExposedPlugin.java, packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/JsonValuePlugin.java
Currently, the project cannot be compiled in VS Code because it complains that 
```
Type mismatch: cannot convert from List<Class<capture#1-of ?>> to List<Class<?>>
```
This is not a real error but a problem in the Eclipse compiler.  his change makes the code compile also with VS Code / Eclipse
=> chore: Change the code so Eclipse JDT accepts it is ok

pom.xml
Hilla pins a couple of dependencies older than the ones defined by Flow. The clash is shown when Vaadin maven plugin fails for some reason and it dumps the project-plugin incompatibilities.
References vaadin/flow#20740
=> chore: align dependencies version with Flow

package.json, packages/ts/react-signals/package.json
Major version 3 drops support for auto tracking, not in use in Hilla anymore
=> chore: Bump preact signals

packages/java/gradle-plugin/src/main/kotlin/com/vaadin/hilla/gradle/plugin/HillaPlugin.kt
To avoid loading Hilla Gradle tasks in projects without Spring, this PR adds a check in the plugin declaration.
=> feat(gradle-plugin): add check for Spring Boot plugin

packages/java/engine-core/src/main/java/com/vaadin/hilla/engine/AotBrowserCallableFinder.java
Fixes #3117 by allowing the class loader used to load endpoints to stay available during class parsing.
=> fix(aot): don't auto-close class loader

package-lock.json, package.json
This should let the tests pass again on GitHub CI
=> chore(ci): install missing monocart-coverage-reports

packages/ts/lit-form/src/BinderRoot.ts, packages/ts/lit-form/test/Validation.test.ts
As the square bracket array syntax comes directly from Java valdiation, I preferred not to touch at the generated exception messages.
Instead, the binder now converts the notation on the fly when parsing the error message, so that it will work in the form.
Fixes #3099
=> fix(binder): convert property paths in arrays to dot notation

.github/workflows/validation.yml, package-lock.json, scripts/vite/browser.vitest.config.ts
If you want to get rid of an additional Chrome binary in your `node_modules`, you can add the following environment variables:
```
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
CHROME_BIN=/opt/google/chrome/chrome # or any other path to your Chrome binary
```
**Note**: if you have `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` set without `CHROME_BIN`, it will throw an error.
**Note**: for this change to take effect you have to run `npm ci`.
=> test: add fallback for Playwright-provided browser

packages/java/endpoint/pom.xml, packages/java/engine-core/pom.xml, packages/java/engine-runtime/pom.xml, packages/java/maven-plugin/pom.xml, packages/java/parser-jvm-core/pom.xml, packages/java/parser-jvm-plugin-backbone/pom.xml, packages/java/parser-jvm-plugin-model/pom.xml, packages/java/parser-jvm-plugin-nonnull/pom.xml, packages/java/parser-jvm-plugin-subtypes/pom.xml, packages/java/parser-jvm-plugin-transfertypes/pom.xml, packages/java/parser-jvm-test-utils/pom.xml, packages/java/parser-jvm-utils/pom.xml, pom.xml
flow and hilla are using the same version of `org.jspecify:jspecify`. so use the transitive dependency from flow-server is simpler for maintenance
=> chore: simplify the jspecify version management in hilla

packages/ts/frontend/src/Connect.ts, packages/ts/frontend/test/Connect.test.ts
Introduce a `mute` option that prevents updating the connection state during requests.
This can be used to not show the progress indicator for calls that are expected to take time.
Closes #2405.
=> feat(connect): add `mute` option to `init` for connection state control

scripts/prepare/templates/components/lit/package.json, scripts/prepare/templates/components/react/package.json
Adds new plugin to templates so that new projects get it added automatically.
=> fix: add new `transfertypes` plugin to new projects

packages/java/gradle-plugin/build.gradle, packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/EndpointExposedPlugin.java
This pull request fixes the production mode build of application using Crud services and possibly other cases.
* [`packages/java/gradle-plugin/build.gradle`](diffhunk://#diff-11e376bdc8ba82f59018f258fef4347682f62c30ce8b1b4183ee5b1fcd8ad89bL70): Removed the `com.vaadin:hilla-endpoint` dependency as it is probably a leftover.
* [`packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/EndpointExposedPlugin.java`](diffhunk://#diff-e39d2a245ce2536e21481655b3897f52ea848d08fabeb2045013034343c94c16R94-R100): Compare annotations by name as Gradle can proxy them.
=> fix: make Gradle plugin able to build projects that use Crud services

packages/java/engine-core/src/main/java/com/vaadin/hilla/engine/commandrunner/CommandRunner.java, packages/java/engine-core/src/test/java/com/vaadin/hilla/engine/commandrunner/CommandRunnerTest.java
When running commands using `CommandRunner`, their output is easily lost.
This PR modifies `CommandRunner` so that the output goes to the console.
This can be useful when there's an error in the `node` command run by the generator.
=> feat: show output of external commands

packages/java/engine-core/pom.xml, packages/java/engine-core/src/main/java/com/vaadin/hilla/engine/AotBrowserCallableFinder.java, packages/java/engine-core/src/main/java/com/vaadin/hilla/engine/EngineConfiguration.java, packages/java/engine-core/src/main/java/com/vaadin/hilla/engine/LookupBrowserCallableFinder.java, packages/java/engine-core/src/test/java/com/vaadin/hilla/engine/EngineConfigurationTest.java, packages/java/engine-runtime/src/main/java/com/vaadin/hilla/internal/EndpointGeneratorTaskFactoryImpl.java
While AOT has proved to be reliable in most cases, it can fail on some projects and we don't want users to have to struggle with it just to compile their apps for production.
This PR adds a fallback in case of AOT failure. All browser-callable services found in the classpath will be reported, which could lead to generation of some TypeScript files not needed by the final application, but the build system will discard unused code anyway.
Also, to reduce noise in the logs, the output of the AOT process is redirected to a file and only debug messages are used.
Fixes #3297
=> fix(parser): add a fallback if AOT fails

packages/ts/react-crud/src/autocrud.tsx, packages/ts/react-crud/test/autocrud.spec.tsx
Changes the recently introduced `newButton` property to `noNewButton` and hides the empty form when the new property is `true`.
Fixes #3324
=> fix(crud): use `noNewButton` name and fix form visibility

packages/java/endpoint/src/main/java/com/vaadin/hilla/crud/PropertyStringFilterSpecification.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/crud/FilterTest.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/crud/TestObject.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/crud/filter/FilterTransformerTest.java
Allow users to pass a PropertyStringFilter for a UUID field.
Fixes #3362
=> feat: Support UUID filtering in PropertyStringFilter

.github/workflows/validation.yml, package.json, scripts/java/hilla-scripts/pom.xml
Change the way React 18 is installed in its GHA job to utilize Flow versions and alignment scripts. This way we make sure that the 19 → 18 step gets done for entire workspace simultaneusly and guarantee that the same React 18 is used in testing.
=> build: use Flow versions for React 18

packages/ts/file-router/src/runtime/createMenuItems.ts, packages/ts/file-router/src/shared/internal.ts, packages/ts/file-router/src/types.ts, packages/ts/file-router/test/runtime/createMenuItems.spec.ts
Introduce generics to the ViewConfig and related types to allow for more flexible detail objects in menu items and view configurations. 
Depends on https://github.com/vaadin/flow/pull/21311
Closes #2564
=> feat(router): add user-defined `detail` type to `ViewConfig`

pom.xml
in 2.2.2, we keep the scm tag when publishing
=> chore: upgrade vaadin-parent to 2.2.2

.github/workflows/validation.yml
seems the environment variable is not working for concurrency group..
this will lead to unexpected cancelling on jobs.
=> chore: fix variable used in concurrency group

packages/java/endpoint/src/main/java/com/vaadin/hilla/EndpointInvocationException.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/EndpointControllerTest.java, packages/java/endpoint/src/test/java/com/vaadin/hilla/EndpointInvokerTest.java
Introduce specific exception classes for HTTP errors, enhancing clarity and maintainability. This change prevents direct instantiation of the root HTTP exception and promotes the use of more descriptive subclasses.
Note that a couple of curly braces is enough to circumvent, but at least the intent is clear.
=> feat(engine): refactor HTTP exception handling to avoid direct usage of root exception

packages/ts/frontend/src/Authentication.ts, packages/ts/frontend/test/Authentication.test.ts
Transform the `doFormLogout` function to be asynchronous, adding a timeout mechanism to allow existing code to await.
Update related test.
The secondary effect is that users need to continue awaiting if they don't want to ignore the promise.
Fixes #3487
=> fix(frontend): make doFormLayout async and waiting

packages/ts/file-router/src/vite-plugin/createRoutesFromMeta.ts, packages/ts/file-router/test/vite-plugin/createRoutesFromMeta.spec.ts, packages/ts/file-router/test/vite-plugin/fixtures/createRoutesFromMeta/basic.snap.ts, packages/ts/file-router/test/vite-plugin/fixtures/createRoutesFromMeta/duplicated-paths.snap.ts
Always adding children in generated file-router.ts seems not to have side effects and fixes the issue.
Fixes #3563.
=> fix(router): always add children, even if empty

packages/java/tests/spring/react-i18n/src/main/frontend/views/@layout.tsx, packages/java/tests/spring/react-i18n/src/main/resources/vaadin-i18n/translations_es_AR.properties, packages/java/tests/spring/react-i18n/src/test/java/com/vaadin/hilla/test/BasicI18NIT.java, packages/ts/react-i18n/src/index.ts, packages/ts/react-i18n/test/i18n.spec.tsx
vaadin/flow#21636 changed the backend implementation to enable using non-default `I18nProvider`.
This change updates tests to assert new backend behavior.
=> fix(react-i18n): align with Flow i18n backend behavior

packages/java/tests/spring/security/src/test/java/com/vaadin/flow/spring/fusionsecurity/SecurityIT.java
Following the changes in the `LoginOverlayElement` component TestBench API from https://github.com/vaadin/flow-components/pull/7783 and the underlying overlay changes in Vaadin components, this PR changes the test code to use LoginFormElement directly instead of finding it in the overlay.
=> chore: use LoginFormElement directly

packages/java/parser-jvm-test-utils/pom.xml, packages/java/parser-jvm-test-utils/src/main/java/com/vaadin/hilla/parser/testutils/JsonAssertions.java, packages/java/parser-jvm-test-utils/src/main/java/module-info.java
Replace string-based JSON comparison with JSONAssert library to avoid test failures caused by formatting changes like whitespace, indentation, or property ordering. Enhanced error messages now provide both precise field-level diffs and complete JSON context for easier debugging.
Changes:
- Add JSONAssert dependency to parser-jvm-test-utils
- Replace string comparison with structural JSON comparison
- Configure module system to allow JSONAssert automatic modules
- Add enhanced error messages showing full JSON context
- Configure compiler and javadoc plugins for module compatibility
=> fix: improve JSON comparison to provide easier to read errors
